Repository kubernetes/cloud-provider-aws, pull requests merged in 2018-11, with the labels that each got.

#16 Add AWS team as owners
  OWNERS
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, sig/aws, size/S

#9 Create SECURITY_CONTACTS file
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/S

#17 Copy latest version of in-tree provider
  pkg/cloudprovider/providers/aws/BUILD
  pkg/cloudprovider/providers/aws/OWNERS
  pkg/cloudprovider/providers/aws/aws.go
  pkg/cloudprovider/providers/aws/aws_fakes.go
  pkg/cloudprovider/providers/aws/aws_instancegroups.go
  pkg/cloudprovider/providers/aws/aws_loadbalancer.go
  pkg/cloudprovider/providers/aws/aws_loadbalancer_test.go
  pkg/cloudprovider/providers/aws/aws_metrics.go
  pkg/cloudprovider/providers/aws/aws_routes.go
  pkg/cloudprovider/providers/aws/aws_test.go
  pkg/cloudprovider/providers/aws/aws_utils.go
  pkg/cloudprovider/providers/aws/device_allocator.go
  pkg/cloudprovider/providers/aws/device_allocator_test.go
  pkg/cloudprovider/providers/aws/instances.go
  pkg/cloudprovider/providers/aws/instances_test.go
  pkg/cloudprovider/providers/aws/log_handler.go
  pkg/cloudprovider/providers/aws/regions.go
  pkg/cloudprovider/providers/aws/regions_test.go
  pkg/cloudprovider/providers/aws/retry_handler.go
  pkg/cloudprovider/providers/aws/retry_handler_test.go
  pkg/cloudprovider/providers/aws/sets_ippermissions.go
  pkg/cloudprovider/providers/aws/tags.go
  pkg/cloudprovider/providers/aws/tags_test.go
  pkg/cloudprovider/providers/aws/volumes.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, sig/aws, sig/cloud-provider, size/XXL

#22 Add changelog for v0.1.0
  CHANGELOG.md
  changelogs/CHANGELOG-0.1.md
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note-none, sig/aws, sig/cloud-provider, size/S
