Repository kubernetes/cloud-provider-aws, pull requests merged in 2019-02, with the labels that each got.

#31 Fix build
  README.md
  cmd/aws-cloud-controller-manager/main.go
Labels: approved, cncf-cla: yes, lgtm, needs-kind, release-note-none, size/XS

#24 Add NOTICE and third-party attribution
  NOTICE
  THIRD-PARTY-LICENSES
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note-none, sig/aws, sig/cloud-provider, size/XXL

#23 Add GitHub templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/failing-test.md
  .github/ISSUE_TEMPLATE/support.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note-none, sig/aws, sig/cloud-provider, size/L

#26 removed trailing comma from Master policy in README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, needs-kind, ok-to-test, release-note-none, size/XS
