Repository kubernetes/cloud-provider-aws, pull requests merged in 2020-05, with the labels that each got.

#94 add initial gitbooks configuration for documentation site
  docs/book/README.md
  docs/book/SUMMARY.md
  hack/build-gitbooks.sh
  netlify.toml
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/M

#96 Fix JSON for node role in README
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/M

#97 Fixed typo
  README.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note-none, size/XS

#95 move inactive approvers to emeritus_approvers
  OWNERS
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/S

#105 Add make targets for pushing to staging GCR repo
  Makefile
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note-none, size/S
