Repository kubernetes/cloud-provider-aws, pull requests merged in 2020-11, with the labels that each got.

#152 Add cloud config for tags
  go.mod
  go.sum
  hack/boilerplate.go.txt
  hack/tools.go
  hack/update-codegen.sh
  hack/verify-codegen.sh
  pkg/apis/config/doc.go
  pkg/apis/config/register.go
  pkg/apis/config/v1alpha1/doc.go
  pkg/apis/config/v1alpha1/register.go
  pkg/apis/config/v1alpha1/types.go
  pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/L

#153 add verify-codegen in CI check
  Makefile
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/XS

#138 Makefile target to build and push image for release
  Makefile
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note-none, size/M
