Repository kubernetes/cloud-provider-aws, pull requests merged in 2020-01, with the labels that each got.

#62 Add missing elasticloadbalancing:DeregisterTargets IAM permission
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/XS

#68 Use v1.17.0 version of legacy cloud provider
  cmd/aws-cloud-controller-manager/main.go
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note-none, size/XL

#70 add dockerfile for containerization
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, needs-kind, ok-to-test, release-note-none, size/M

#71 change dockerfile to distroless, use make
  Dockerfile
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note-none, size/S
