Repository kubernetes/cloud-provider-aws, pull requests merged in 2020-12, with the labels that each got.

#159 Fix build command
  Makefile
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note-none, size/XS

#161 Add docs publishing script and improve documentation
  Makefile
  README.md
  docs/assets/images/aws_logo.svg
  docs/assets/images/kubernetes_icon.svg
  docs/book/SUMMARY.md
  docs/book/development.md
  docs/book/getting_started.md
  docs/book/iam_policy.md
  hack/publish-docs.sh
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/L

#162 Fix cloudbuild and simplify Makefile & cloudbuild
  Dockerfile
  Makefile
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/M

#163 Fix cloudbuild image name
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, needs-kind, release-note-none, size/XS

#151 Bump k8s.io/kubernetes@v1.20.0
  cmd/aws-cloud-controller-manager/main.go
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/XL

#164 Pass in cloud config file to initialize cloud provider
  cmd/aws-cloud-controller-manager/main.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note-none, size/XS

#157 Add ECR creds provider
  .gitignore
  Makefile
  cmd/ecr-credential-provider/main.go
  cmd/ecr-credential-provider/main_test.go
  cmd/ecr-credential-provider/plugin.go
  cmd/ecr-credential-provider/plugin_test.go
  go.mod
  go.sum
  pkg/providers/v2/mocks/mock_ecr.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note, size/XL

#165 Docs
  .gitignore
  docs/book/README.md
  docs/book/SUMMARY.md
  docs/book/TODO.md
  docs/book/getting_started.md
  docs/book/iam_policy.md
  docs/book/known_limitations.md
  docs/book/prerequisites.md
  docs/book/service_loadbalancers.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, release-note-none, size/L

#166 Update the docs
  docs/TODO.md
  docs/development.html
  docs/getting_started.html
  docs/iam_policy.html
  docs/index.html
  docs/known_limitations.html
  docs/package-lock.json
  docs/prerequisites.html
  docs/search_index.json
  docs/service_loadbalancers.html
Labels: cncf-cla: yes, kind/documentation, lgtm, needs-ok-to-test, release-note-none, size/XXL

#167 Migrate to mkdocs
  .github/workflows/publish_docs.yml
  docs/book/README.md
  docs/book/getting_started.md
  docs/book/index.md
  mkdocs.yml
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, release-note-none, size/M
