Repository kubernetes/cloud-provider-aws, pull requests merged in 2020-03, with the labels that each got.

#82 docs(README.md): Fixing JSON codeblock for valid JSON for the AWS con…
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note, size/XS

#83 Vendor kubernetes/kubernetes@v1.18.0
  Dockerfile
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note-none, size/L

#84 add sig-release
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, lgtm, needs-kind, ok-to-test, release-note, size/XS
