Repository kubernetes/cloud-provider-aws, pull requests merged in 2020-09, with the labels that each got.

#126 Initial changes for compatibility with v1.19
  Makefile
  cmd/aws-cloud-controller-manager/main.go
  go.mod
  go.sum
  pkg/providers/v2/interface.go
Labels: approved, cncf-cla: yes, lgtm, needs-kind, release-note-none, size/XL

#129 Create a new instance of aws cloud
  go.mod
  pkg/providers/v2/cloud.go
  pkg/providers/v2/cloud_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note, size/L

#132 fix typo
  pkg/providers/v1/install.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note-none, size/XS

#133 Merging master into 1.19
  Makefile
  cmd/aws-cloud-controller-manager/main.go
  go.mod
  go.sum
  pkg/providers/v1/install.go
  pkg/providers/v2/cloud.go
  pkg/providers/v2/cloud_test.go
  pkg/providers/v2/interface.go
Labels: approved, cncf-cla: yes, lgtm, needs-kind, release-note-none, size/XL

#134 Release 1.19
  manifests/aws-cloud-controller-manager-daemonset.yaml
Labels: approved, cncf-cla: yes, lgtm, needs-kind, release-note-none, size/XS

#136 Fix Dockerfile to add files in /pkg folder
  Dockerfile
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note-none, size/XS
