Repository kubernetes/cloud-provider-aws, pull requests merged in 2020-07, with the labels that each got.

#112 Fixed broken link
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#115 bump k8s.io/kubernetes to v1.18.6
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/M

#116 bump image version in example manifests to v1.18.0-alpha.1
  manifests/aws-cloud-controller-manager-daemonset.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/XS

#114 add initial experimental v2 AWS cloud provider
  cmd/aws-cloud-controller-manager/main.go
  pkg/providers/v1/install.go
  pkg/providers/v2/interface.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/L

#118 Clean up whitespace in README
  README.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/M
