Repository kubernetes/cloud-provider-aws, pull requests merged in 2020-10, with the labels that each got.

#139 Merge master into release-1.19
  Dockerfile
  manifests/aws-cloud-controller-manager-daemonset.yaml
Labels: approved, cncf-cla: yes, lgtm, needs-kind, release-note-none, size/XS

#140 latest manifest should point to v1.19.0-alpha.1, not v1.19.1-alpha.1
  manifests/aws-cloud-controller-manager-daemonset.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#141 Merge master into release-1.19
  manifests/aws-cloud-controller-manager-daemonset.yaml
Labels: approved, cncf-cla: yes, lgtm, needs-kind, release-note-none, size/XS

#131 instances: initial implementation of instancesV2 interface
  go.mod
  go.sum
  pkg/providers/v2/cloud.go
  pkg/providers/v2/instances.go
  pkg/providers/v2/instances_test.go
  pkg/providers/v2/mocks/mock_ec2.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note, size/XL

#147 Update Flags section of README
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, release-note-none, size/XS

#146 Update go modules to include latest k8s.io/kubernetes module on v-1.19
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/L

#150 Bump the go version to v1.15 latest
  Dockerfile
  go.mod
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/XS
