Repository kubernetes/cloud-provider-aws, pull requests merged in 2021-04, with the labels that each got.

#197 Add a docs page for the service controller
  docs/service_controller.md
  mkdocs.yml
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/M

#191 Automate helm chart release
  .github/cr.yaml
  .github/workflows/helm_chart_release.yaml
  charts/aws-cloud-controller-manager/Chart.yaml
  charts/aws-cloud-controller-manager/Readme.md
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note-none, size/M

#205 Bump dependencies to v1.21.0
  cmd/aws-cloud-controller-manager/main.go
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, needs-kind, release-note-none, size/XL

#207 Add Makefile target for windows binary
  .gitignore
  Makefile
Labels: approved, cncf-cla: yes, lgtm, needs-kind, release-note-none, size/XS
