Repository kubernetes/cloud-provider-aws, pull requests merged in 2021-05, with the labels that each got.

#211 Cherry-pick: Use GA topoogy labels for EBS (#99130)
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_test.go
Labels: approved, cncf-cla: yes, lgtm, needs-kind, release-note-none, size/S

#212 Cherry-pick: delete leaked volume if driver don't know the volume status -- aws (#99664)
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/M

#210 Cherry-pick: additional subnet configuration for AWS ELB (#97431)
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_test.go
  pkg/providers/v1/tags.go
  pkg/providers/v1/tags_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note-none, size/XL

#204 A missing item
  docs/getting_started.md
Labels: approved, cncf-cla: yes, lgtm, needs-kind, ok-to-test, release-note-none, size/XS

#215 Changelog 1.21
  docs/CHANGELOG.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S
