Repository kubernetes/cloud-provider-aws, pull requests merged in 2021-12, with the labels that each got.

#290 Update go to v1.17.4
  Dockerfile
  go.mod
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup

#289 Add support for ARM64 builds
  Dockerfile
  Makefile
  cloudbuild.yaml
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/M, release-note

#291 Update k8s dependencies to v1.23.0
  go.mod
  go.sum
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L, release-note

#292 Update aws-sdk-go to v1.42.20
  go.mod
  go.sum
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/XS, release-note

#295 Use go-runner as base image
  Dockerfile
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/S, release-note-none
