Repository kubernetes/cloud-provider-aws, pull requests merged in 2021-02, with the labels that each got.

#149 tags: initial implementation of tags
  go.mod
  pkg/providers/v2/cloud.go
  pkg/providers/v2/cloud_test.go
  pkg/providers/v2/instances.go
  pkg/providers/v2/mocks/mock_ec2.go
  pkg/providers/v2/tags.go
  pkg/providers/v2/tags_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note-none, size/XL

#172 Add wongma7 to owners
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, needs-kind, release-note-none, size/XS

#160 Merge legacy provider
  go.mod
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_fakes.go
  pkg/providers/v1/aws_instancegroups.go
  pkg/providers/v1/aws_loadbalancer.go
  pkg/providers/v1/aws_loadbalancer_test.go
  pkg/providers/v1/aws_metrics.go
  pkg/providers/v1/aws_routes.go
  pkg/providers/v1/aws_test.go
  pkg/providers/v1/aws_utils.go
  pkg/providers/v1/device_allocator.go
  pkg/providers/v1/device_allocator_test.go
  pkg/providers/v1/doc.go
  pkg/providers/v1/instances.go
  pkg/providers/v1/instances_test.go
  pkg/providers/v1/log_handler.go
  pkg/providers/v1/retry_handler.go
  pkg/providers/v1/retry_handler_test.go
  pkg/providers/v1/sets_ippermissions.go
  pkg/providers/v1/tags.go
  pkg/providers/v1/tags_test.go
  pkg/providers/v1/volumes.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/XXL

#173 feat: Helm chart for aws cloud controller manager
  charts/aws-cloud-controller-manager/Chart.yaml
  charts/aws-cloud-controller-manager/LICENSE
  charts/aws-cloud-controller-manager/Readme.md
  charts/aws-cloud-controller-manager/templates/NOTES.txt
  charts/aws-cloud-controller-manager/templates/_helpers.tpl
  charts/aws-cloud-controller-manager/templates/cluserrolebinding.yaml
  charts/aws-cloud-controller-manager/templates/clusterrole.yaml
  charts/aws-cloud-controller-manager/templates/daemonset.yaml
  charts/aws-cloud-controller-manager/templates/rolebinding.yaml
  charts/aws-cloud-controller-manager/templates/serviceaccount.yaml
  charts/aws-cloud-controller-manager/values.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note, size/L

#175 Add released versions to README
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S

#174 Add documentation for cred provider
  docs/book/credential_provider.md
  docs/book/index.md
  mkdocs.yml
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, release-note-none, size/M

#170 update klog library from 2.4.0 to 2.5.0
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note-none, size/XS

#176 Replace book homepage with README
  docs/README.md
  docs/TODO.md
  docs/book/README.md
  docs/book/index.md
  docs/credential_provider.md
  docs/development.md
  docs/getting_started.md
  docs/prerequisites.md
  hack/build-gitbooks.sh
  mkdocs.yml
  netlify.toml
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/M

#179 Add script to generate changelog
  hack/changelog.py
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/M

#178 Add release github workflow
  .github/workflows/release.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note-none, size/M

#182 Document release process
  .github/workflows/release.yaml
  .gitignore
  CHANGELOG.md
  docs/CHANGELOG.md
  docs/RELEASE.md
  hack/changelog.py
  mkdocs.yml
Labels: approved, cncf-cla: yes, lgtm, needs-kind, release-note-none, size/L
