Repository kubernetes/cloud-provider-aws, pull requests merged in 2021-03, with the labels that each got.

#183 Release 1.20
  .github/workflows/release.yaml
  .gitignore
  CHANGELOG.md
  charts/aws-cloud-controller-manager/Chart.yaml
  charts/aws-cloud-controller-manager/values.yaml
  docs/CHANGELOG.md
  docs/README.md
  docs/RELEASE.md
  hack/changelog.py
  manifests/aws-cloud-controller-manager-daemonset.yaml
  mkdocs.yml
Labels: approved, cncf-cla: yes, lgtm, needs-kind, release-note-none, size/L

#186 Release v1.20.0-alpha.1
  charts/aws-cloud-controller-manager/Chart.yaml
  charts/aws-cloud-controller-manager/values.yaml
  docs/CHANGELOG.md
  docs/README.md
  manifests/aws-cloud-controller-manager-daemonset.yaml
Labels: approved, cncf-cla: yes, lgtm, needs-kind, release-note-none, size/M

#189 Fix version
  charts/aws-cloud-controller-manager/Chart.yaml
  charts/aws-cloud-controller-manager/values.yaml
  docs/CHANGELOG.md
  docs/README.md
  manifests/aws-cloud-controller-manager-daemonset.yaml
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S

#190 Remove docs publish gh workflow
  .github/workflows/publish_docs.yml
  docs/README.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/S

#193 Fixing broken KEP link
  docs/README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note, size/XS

#194 Add self to OWNERS
  OWNERS
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS
