Repository kubernetes/cloud-provider-aws, pull requests merged in 2021-09, with the labels that each got.

#251 Make Node IP families configurable
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note, needs-kind

#250 Fix copy/paste error in IPPermissionSet.Ungroup
  pkg/providers/v1/sets_ippermissions.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/XS, release-note-none

#266 Remove inactive and add jaypipes
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind

#265 Add a unit test for sets_ippermissions
  pkg/providers/v1/sets_ippermissions_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup

#268 Changelog v1.22.0-alpha.0
  docs/CHANGELOG.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/S, release-note-none

#267 Use promoted images
  charts/aws-cloud-controller-manager/values.yaml
  manifests/base/aws-cloud-controller-manager-daemonset.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup

#274 Set MaxResults if it is not set
  pkg/providers/v1/aws.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/XS, release-note

#273 [helm] Command line flags can be overridden
  charts/aws-cloud-controller-manager/Chart.yaml
  charts/aws-cloud-controller-manager/templates/daemonset.yaml
  charts/aws-cloud-controller-manager/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note, kind/cleanup

#277 Add test for DescribeInstances
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup
