Repository kubernetes/cloud-provider-aws, pull requests merged in 2022-01, with the labels that each got.

#293 Tag on create
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note, needs-kind

#297 Release v1.23.0-alpha.0
  .github/workflows/helm_chart_release.yaml
  docs/CHANGELOG.md
  docs/README.md
  docs/RELEASE.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/L, release-note-none

#298 Update charts for v1.23.0-alpha.0
  charts/aws-cloud-controller-manager/Chart.yaml
  charts/aws-cloud-controller-manager/values.yaml
  examples/existing-cluster/base/aws-cloud-controller-manager-daemonset.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup
