Repository kubernetes/cloud-provider-aws, pull requests merged in 2022-09, with the labels that each got.

#487 Automated cherry pick of #484: Handle wrapped error for InvalidInstanceID.NotFound in
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, needs-ok-to-test, needs-kind, needs-triage

#488 Automated cherry pick of #484: Handle wrapped error for InvalidInstanceID.NotFound in
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, needs-ok-to-test, needs-kind, needs-triage

#486 Automated cherry pick of #484: Handle wrapped error for InvalidInstanceID.NotFound in
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, needs-kind, ok-to-test, needs-triage

#485 Automated cherry pick of #484: Handle wrapped error for InvalidInstanceID.NotFound in
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, needs-kind, ok-to-test, needs-triage

#484 Handle wrapped error for InvalidInstanceID.NotFound in InstanceExistsByProviderID
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_test.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/S, release-note-none, ok-to-test, needs-triage

#479 Bump version to 1.22.5
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, needs-triage

#482 Bump version to 1.23.3
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, needs-triage

#490 Automated cherry pick of #302: Fix target group instances registration when TG created
  pkg/providers/v1/aws_loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, triage/accepted

#494 Bump to version 1.23.4
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, needs-triage

#492 Automated cherry pick of #412: Add rate limiting when calling STS assume role API
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_assumerole_provider.go
  pkg/providers/v1/aws_assumerole_provider_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, needs-kind, ok-to-test, needs-triage

#493 Automated cherry pick of #412: Add rate limiting when calling STS assume role API
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_assumerole_provider.go
  pkg/providers/v1/aws_assumerole_provider_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, needs-kind, ok-to-test, needs-triage

#495 Bump version to 1.20.4
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, needs-triage

#496 Bump version to 1.21.4
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, needs-triage

#500 Bump netlify Python for to v3.8
  netlify.toml
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup, needs-triage

#510 update aws-sdk-go to v1.44.107
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, needs-triage

#511 Updated awd-sdk-go to v1.44.107
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup, ok-to-test, needs-triage

#504 updated aws-sdk-go to v1.44.107
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup, ok-to-test, needs-triage
