Repository kubernetes/cloud-provider-aws, pull requests merged in 2022-06, with the labels that each got.

#302 Fix target group instances registration when TG created
  pkg/providers/v1/aws_loadbalancer.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/XS, release-note-none, ok-to-test

#397 Add hakman to owners file
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#395 Bump kubernetes version for e2e to 1.24.1
  go.mod
  go.sum
  hack/e2e/run.sh
  hack/install-e2e-tools.sh
  tests/e2e/go.mod
  tests/e2e/go.sum
  tests/e2e/loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup, needs-triage

#408 Fix the kops-example script
  examples/kops-new-cluster/base/cluster.yaml
  examples/kops-new-cluster/overlays/cloud-controller-manager/cluster.yaml
  hack/kops-example.sh
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note, kind/cleanup, needs-triage

#407 Add make targets for building with ko
  .ko.yaml
  Makefile
  hack/install-ko.sh
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/M, release-note-none, needs-triage

#409 Add note about node naming conventions
  docs/prerequisites.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/XS, release-note, needs-triage

#365 Changelogs
  docs/CHANGELOG.md
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/M, release-note-none, needs-triage

#411 Add rate limiting support for Tagging Controller
  pkg/controllers/options/tagging_controller.go
  pkg/controllers/tagging/tagging_controller.go
  pkg/controllers/tagging/tagging_controller_test.go
  pkg/controllers/tagging/tagging_controller_wrapper.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/M, release-note, ok-to-test, triage/accepted

#413 Add rate limiting support for Tagging Controller
  go.mod
  pkg/controllers/options/tagging_controller.go
  pkg/controllers/tagging/tagging_controller.go
  pkg/controllers/tagging/tagging_controller_test.go
  pkg/controllers/tagging/tagging_controller_wrapper.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/M, release-note, ok-to-test, triage/accepted

#416 Add rate limiting support for Tagging Controller
  pkg/controllers/options/tagging_controller.go
  pkg/controllers/tagging/tagging_controller.go
  pkg/controllers/tagging/tagging_controller_test.go
  pkg/controllers/tagging/tagging_controller_wrapper.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/M, release-note, ok-to-test, triage/accepted

#414 Add rate limiting support for Tagging Controller
  go.mod
  pkg/controllers/options/tagging_controller.go
  pkg/controllers/tagging/tagging_controller.go
  pkg/controllers/tagging/tagging_controller_test.go
  pkg/controllers/tagging/tagging_controller_wrapper.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/M, release-note, ok-to-test, triage/accepted

#415 Add rate limiting support for Tagging Controller
  pkg/controllers/options/tagging_controller.go
  pkg/controllers/tagging/tagging_controller.go
  pkg/controllers/tagging/tagging_controller_test.go
  pkg/controllers/tagging/tagging_controller_wrapper.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/M, release-note, ok-to-test, triage/accepted

#418 Update dependencies
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup, needs-triage

#405 Automated cherry pick of #388: Tag releases automatically #396: Fetch all history when tagging releases
  .github/workflows/tag-release.yml
  hack/tag-release.sh
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, needs-kind, needs-triage

#421 Automated cherry pick of #313: add sts regional endpoint logic
  pkg/providers/v1/aws.go
Labels: approved, cncf-cla: yes, lgtm, size/M, needs-kind, ok-to-test, triage/accepted

#425 Create tags for new release
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, triage/accepted

#423 Create tags for new release
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, triage/accepted

#424 Create tags for new release
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, triage/accepted

#426 Create tags for new release
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, triage/accepted
