Repository kubernetes/cloud-provider-aws, pull requests merged in 2022-05, with the labels that each got.

#345 Double load balancer timeout from 5 mins to 10
  tests/e2e/loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/flake, needs-triage

#346 Automated cherry pick of #345: Double load balancer timeout from 5 mins to 10
  tests/e2e/loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#347 Automated cherry pick of #345: Double load balancer timeout from 5 mins to 10
  tests/e2e/loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#344 Bump k8s.io deps to 1.24.0
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, needs-kind, needs-triage

#334 [Issue #325] Added retry count to abort workitem after a few failed retries
  docs/TODO.md
  pkg/controllers/tagging/metrics.go
  pkg/controllers/tagging/tagging_controller.go
  pkg/controllers/tagging/tagging_controller_test.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L, release-note-none, ok-to-test, triage/accepted

#350 Trim date prefix from tag in GCB image build
  cloudbuild.yaml
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-triage

#352 Use short git tag for version and images
  cloudbuild.yaml
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/XS, release-note-none, triage/accepted

#354 Explain short tag with comment
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#353 Automated cherry pick of #352: Use short git tag for version and images
  cloudbuild.yaml
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/XS, release-note-none, triage/accepted

#355 Update Go to v1.18.1
  Dockerfile
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/XS, release-note-none, triage/accepted

#357 Automated cherry pick of #308: Add tagging controller configuration #334: Stop retrying failed workitem after a certain amount of
  .gitignore
  Dockerfile
  Makefile
  cmd/aws-cloud-controller-manager/main.go
  docs/TODO.md
  docs/tagging_controller.md
  go.mod
  pkg/controllers/options/resources.go
  pkg/controllers/options/tagging_controller.go
  pkg/controllers/tagging/metrics.go
  pkg/controllers/tagging/tagging_controller.go
  pkg/controllers/tagging/tagging_controller_test.go
  pkg/controllers/tagging/tagging_controller_wrapper.go
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_fakes.go
  pkg/providers/v1/tags.go
Labels: do-not-merge/hold, cncf-cla: yes, size/XL, release-note-none, needs-ok-to-test, needs-kind, needs-triage

#358 Automated cherry pick of #308: Add tagging controller configuration #334: Stop retrying failed workitem after a certain amount of
  .gitignore
  Dockerfile
  Makefile
  cmd/aws-cloud-controller-manager/main.go
  docs/TODO.md
  docs/tagging_controller.md
  go.mod
  pkg/controllers/options/resources.go
  pkg/controllers/options/tagging_controller.go
  pkg/controllers/tagging/metrics.go
  pkg/controllers/tagging/tagging_controller.go
  pkg/controllers/tagging/tagging_controller_test.go
  pkg/controllers/tagging/tagging_controller_wrapper.go
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_fakes.go
  pkg/providers/v1/tags.go
Labels: cncf-cla: yes, size/XL, do-not-merge/release-note-label-needed, needs-ok-to-test, needs-kind, needs-triage

#361 Automated cherry pick of #205: Bump dependencies to v1.21.0 #308: Add tagging controller configuration #334: Stop retrying failed workitem after a certain amount of
  .gitignore
  Dockerfile
  Makefile
  cmd/aws-cloud-controller-manager/main.go
  docs/TODO.md
  docs/tagging_controller.md
  go.mod
  go.sum
  pkg/controllers/options/resources.go
  pkg/controllers/options/tagging_controller.go
  pkg/controllers/tagging/metrics.go
  pkg/controllers/tagging/tagging_controller.go
  pkg/controllers/tagging/tagging_controller_test.go
  pkg/controllers/tagging/tagging_controller_wrapper.go
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_fakes.go
  pkg/providers/v1/tags.go
Labels: cncf-cla: yes, do-not-merge/release-note-label-needed, needs-ok-to-test, size/XXL, needs-kind, needs-triage

#364 Release v1.24.0
  docs/CHANGELOG.md
  hack/changelog.py
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/S, release-note-none, triage/accepted

#332 Bump dependencies
  go.mod
  go.sum
  hack/tools.go
  pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_fakes.go
  pkg/providers/v1/aws_instancegroups.go
  pkg/providers/v1/aws_loadbalancer.go
  pkg/providers/v1/aws_loadbalancer_test.go
  pkg/providers/v1/aws_metrics.go
  pkg/providers/v1/aws_routes.go
  pkg/providers/v1/aws_test.go
  pkg/providers/v1/aws_utils.go
  pkg/providers/v1/device_allocator.go
  pkg/providers/v1/device_allocator_test.go
  pkg/providers/v1/instances.go
  pkg/providers/v1/instances_test.go
  pkg/providers/v1/log_handler.go
  pkg/providers/v1/retry_handler.go
  pkg/providers/v1/retry_handler_test.go
  pkg/providers/v1/sets_ippermissions.go
  pkg/providers/v1/tags.go
  pkg/providers/v1/tags_test.go
  pkg/providers/v1/volumes.go
Labels: approved, cncf-cla: yes, size/L, release-note-none, kind/cleanup, needs-triage

#371 go fmt release-1.20
  go.mod
  go.sum
  hack/tools.go
  pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_fakes.go
  pkg/providers/v1/aws_instancegroups.go
  pkg/providers/v1/aws_loadbalancer.go
  pkg/providers/v1/aws_loadbalancer_test.go
  pkg/providers/v1/aws_metrics.go
  pkg/providers/v1/aws_routes.go
  pkg/providers/v1/aws_test.go
  pkg/providers/v1/aws_utils.go
  pkg/providers/v1/device_allocator.go
  pkg/providers/v1/device_allocator_test.go
  pkg/providers/v1/instances.go
  pkg/providers/v1/instances_test.go
  pkg/providers/v1/log_handler.go
  pkg/providers/v1/retry_handler.go
  pkg/providers/v1/retry_handler_test.go
  pkg/providers/v1/sets_ippermissions.go
  pkg/providers/v1/tags.go
  pkg/providers/v1/tags_test.go
  pkg/providers/v1/volumes.go
Labels: approved, cncf-cla: yes, size/M, release-note-none, kind/cleanup, needs-triage

#366 Fix issue with flag causing test failures in 1.22
  pkg/controllers/tagging/tagging_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, kind/failing-test, size/XS, release-note-none, ok-to-test, triage/accepted

#370 Cherry pick E2E test changes and fix failing tagging controller test for 1.20
  hack/e2e/run.sh
  hack/install-e2e-tools.sh
  pkg/controllers/tagging/tagging_controller_test.go
  tests/e2e/go.mod
  tests/e2e/go.sum
  tests/e2e/loadbalancer.go
  tests/e2e/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XXL, needs-kind, ok-to-test, triage/accepted

#369 Cherry pick E2E test changes and fix failing tagging controller test for 1.21
  hack/e2e/run.sh
  hack/install-e2e-tools.sh
  pkg/controllers/tagging/tagging_controller_test.go
  tests/e2e/go.mod
  tests/e2e/go.sum
  tests/e2e/loadbalancer.go
  tests/e2e/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XXL, needs-kind, ok-to-test, triage/accepted

#372 Add olemarkus to owners file
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#363 Automated cherry pick of #352: Use short git tag for version and images
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, triage/accepted

#374 Update cloud build config for v1.21
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup, triage/accepted

#375 Update cloud build config for v1.20
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup, triage/accepted

#373 Add note about AWS CCM container images
  charts/aws-cloud-controller-manager/values.yaml
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/XS, release-note-none, ok-to-test, needs-triage

#376 Stop tagging latest for release branches
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup, triage/accepted

#380 Make build targets phony
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup, needs-triage

#382 Automated cherry pick of #376: Stop tagging latest for release branches
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, triage/accepted

#383 Automated cherry pick of #376: Stop tagging latest for release branches
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, triage/accepted

#381 Automated cherry pick of #376: Stop tagging latest for release branches
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, triage/accepted

#387 [FIXES] [Tagging Controller] Fix issues in tagging controller
  pkg/controllers/tagging/metrics.go
  pkg/controllers/tagging/tagging_controller.go
  pkg/controllers/tagging/tagging_controller_test.go
  pkg/providers/v1/aws.go
  pkg/providers/v1/instances.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/L, release-note, ok-to-test, needs-triage

#389 [Cherry Pick from master to 1.22] [FIXES] [Tagging Controller] Fix issues in tagging controller
  pkg/controllers/tagging/metrics.go
  pkg/controllers/tagging/tagging_controller.go
  pkg/controllers/tagging/tagging_controller_test.go
  pkg/providers/v1/aws.go
  pkg/providers/v1/instances.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/L, release-note, ok-to-test, triage/accepted

#392 Automated cherry pick of #223: Add ENI support for nodes(for Fargate nodes) #387: Fix issues in tagging controller
  pkg/controllers/tagging/metrics.go
  pkg/controllers/tagging/tagging_controller.go
  pkg/controllers/tagging/tagging_controller_test.go
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_fakes.go
  pkg/providers/v1/aws_test.go
  pkg/providers/v1/instances.go
  pkg/providers/v1/instances_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, needs-kind, ok-to-test, triage/accepted

#388 Tag releases automatically
  .github/workflows/tag-release.yml
  docs/RELEASE.md
  hack/tag-release.sh
  version.txt
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/M, release-note-none, needs-triage

#396 Fetch all history when tagging releases
  .github/workflows/tag-release.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup, triage/accepted

#393 Automated cherry pick of #308: Add tagging controller configuration #334: Stop retrying failed workitem after a certain amount of #387: Fix issues in tagging controller
  .gitignore
  cmd/aws-cloud-controller-manager/main.go
  docs/TODO.md
  docs/tagging_controller.md
  pkg/controllers/options/resources.go
  pkg/controllers/options/tagging_controller.go
  pkg/controllers/tagging/metrics.go
  pkg/controllers/tagging/tagging_controller.go
  pkg/controllers/tagging/tagging_controller_test.go
  pkg/controllers/tagging/tagging_controller_wrapper.go
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_fakes.go
  pkg/providers/v1/instances.go
  pkg/providers/v1/tags.go
Labels: approved, cncf-cla: yes, lgtm, size/XL, release-note-none, needs-kind, ok-to-test, triage/accepted
