Repository kubernetes/cloud-provider-aws, pull requests merged in 2022-04, with the labels that each got.

#330 Bump dependencies
  Makefile
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup, needs-triage

#328 Add environment and securityContexts
  charts/aws-cloud-controller-manager/Readme.md
  charts/aws-cloud-controller-manager/templates/daemonset.yaml
  charts/aws-cloud-controller-manager/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note, kind/cleanup, ok-to-test, needs-triage

#329 Bump dependency versions
  Makefile
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup, needs-triage

#331 Bump dependencies
  Makefile
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup, needs-triage

#333 chart: Add extraVolumes and extraVolumeMounts
  charts/aws-cloud-controller-manager/templates/daemonset.yaml
  charts/aws-cloud-controller-manager/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note, kind/cleanup, ok-to-test, needs-triage

#336 Docs
  docs/CHANGELOG.md
  docs/README.md
  hack/changelog.py
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/M, release-note-none, needs-triage

#337 Update changelog and readme with v1.23.0 and v1.24.0-alpha.0
  docs/CHANGELOG.md
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/S, release-note-none, needs-triage
