Repository kubernetes/cloud-provider-aws, pull requests merged in 2022-12, with the labels that each got.

#532 Run e2e tests with `--dns=none`
  hack/e2e/run.sh
Labels: approved, cncf-cla: yes, lgtm, kind/failing-test, size/XS, release-note-none, triage/accepted

#531 Bump aws-sdk-go version to 1.44.145
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note, needs-kind, ok-to-test, needs-triage

#533 Bump aws-sdk-go version to 1.44.145 & cherry pick Run e2e tests with --dns=none #532
  go.mod
  go.sum
  hack/e2e/run.sh
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note, needs-kind, ok-to-test, needs-triage

#534 Bump aws-sdk-go version to 1.44.145 & cherry pick Run e2e tests with --dns=none #532
  go.mod
  go.sum
  hack/e2e/run.sh
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note, needs-kind, ok-to-test, needs-triage

#535 Bump aws-sdk-go version to 1.44.145 & cherry pick Run e2e tests with --dns=none #532
  go.mod
  go.sum
  hack/e2e/run.sh
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note, needs-kind, ok-to-test, needs-triage

#537 Bump aws-sdk-go version to 1.44.145 & cherry pick Run e2e tests with --dns=none #532
  go.mod
  go.sum
  hack/e2e/run.sh
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note, needs-kind, ok-to-test, needs-triage

#536 Bump k8s deps to 1.26.0-rc.1
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, needs-kind, needs-triage

#538 Update Go to v1.19.3
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup, needs-triage

#540 Release 1.26.0-rc.1
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#539 Migrate k8s e2e to Ginkgo 2.0
  hack/e2e/run.sh
  tests/e2e/go.mod
  tests/e2e/go.sum
  tests/e2e/loadbalancer.go
  tests/e2e/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL, release-note-none, kind/cleanup, needs-triage

#541 Release 1.26.0-alpha.1
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#546 Bump release version to 1.21.6
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note, needs-kind, ok-to-test, needs-triage

#543 Bump release version to 1.24.3
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note, needs-kind, ok-to-test, needs-triage

#544 Bump release version to 1.23.6
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note, needs-kind, ok-to-test, needs-triage

#527 Restore chunked behaviour of target group creation in LBv2
  pkg/providers/v1/aws_loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup, needs-triage

#530 Update v1 provider isRegionValid name and to return an error
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_test.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/M, release-note, ok-to-test, needs-triage

#503 ecr-credential-provider: clean up docs
  docs/credential_provider.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/S, release-note-none, kind/cleanup, ok-to-test, needs-triage

#547 Bump k8s dependencies to 1.26.0 and golang to 1.19.4
  Dockerfile
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, needs-kind, needs-triage

#549 Bump various dependencies for ccm and e2e tests
  go.mod
  go.sum
  hack/e2e/run.sh
  tests/e2e/go.mod
  tests/e2e/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XL, release-note-none, kind/cleanup, needs-triage

#550 Release 1.26.0
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#499 Restrict subnets only to subnets from regular availability zones in ELB auto-discovery procedure
  docs/prerequisites.md
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_fakes.go
  pkg/providers/v1/aws_test.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L, release-note, ok-to-test, needs-triage

#551 set CCM 1.24 k8s deps to 1.24.9
  .ko.yaml
  Dockerfile
  go.mod
  go.sum
  hack/e2e/run.sh
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/L, release-note-none, needs-triage

#553 Update kOps command for creating clusters
  hack/e2e/run.sh
Labels: approved, cncf-cla: yes, lgtm, kind/failing-test, size/XS, release-note-none, needs-triage

#552 update base image to golang 1.19.4
  .ko.yaml
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup, needs-triage

#554 Bump release version to 1.24.4
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note, needs-kind, needs-triage
