Repository kubernetes/cloud-provider-aws, pull requests merged in 2022-10, with the labels that each got.

#516 Bump to version 1.23.5
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup, ok-to-test, needs-triage

#517 bumped the release version to 1.24.2
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup, ok-to-test, needs-triage

#514 Bump version to 1.22.6
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup, ok-to-test, needs-triage

#515 bumped the release version to 1.21.5
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup, ok-to-test, needs-triage

#522 Bump K8s libs to 0.25.3
  go.mod
  go.sum
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup, ok-to-test, needs-triage

#523 Release version v1.25.1
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage
