Repository kubernetes/cloud-provider-aws, pull requests merged in 2022-08, with the labels that each got.

#446 Revert "Ensure kops cluster is always torn down after e2e run"
  hack/e2e/run.sh
Labels: approved, cncf-cla: yes, lgtm, kind/failing-test, size/S, release-note-none, needs-triage

#447 Update gofmt for go 1.19
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_loadbalancer.go
  pkg/providers/v1/instances.go
  pkg/providers/v1/volumes.go
  pkg/providers/v2/instances.go
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup, needs-triage

#451 E2E tests fix
  hack/e2e/run.sh
Labels: approved, cncf-cla: yes, priority/critical-urgent, lgtm, kind/failing-test, size/XS, release-note-none, needs-triage

#450 Test e2e
  hack/e2e/run.sh
Labels: cncf-cla: yes, do-not-merge/release-note-label-needed, size/XS, needs-kind, needs-triage

#453 Automated cherry pick of #451: Test e2e
  hack/e2e/run.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#455 Automated cherry pick of #451: Test e2e
  hack/e2e/run.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#456 Automated cherry pick of #451: Test e2e
  hack/e2e/run.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#454 Automated cherry pick of #451: Test e2e
  hack/e2e/run.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#449 Automated cherry pick of #412: Add rate limiting when calling STS assume role API
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_assumerole_provider.go
  pkg/providers/v1/aws_assumerole_provider_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, needs-kind, ok-to-test, needs-triage

#457 Automated cherry pick of #412: Add rate limiting when calling STS assume role API
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_assumerole_provider.go
  pkg/providers/v1/aws_assumerole_provider_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, needs-ok-to-test, needs-kind, needs-triage

#462 Automated cherry pick of #448: Handle InvalidInstanceID.NotFound when tagging resources
  pkg/providers/v1/aws_fakes.go
  pkg/providers/v1/tags.go
  pkg/providers/v1/tags_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, needs-kind, ok-to-test, needs-triage

#460 Automated cherry pick of #448: Handle InvalidInstanceID.NotFound when tagging resources
  pkg/providers/v1/aws_fakes.go
  pkg/providers/v1/tags.go
  pkg/providers/v1/tags_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, needs-kind, ok-to-test, needs-triage

#463 Automated cherry pick of #448: Handle InvalidInstanceID.NotFound when tagging resources
  pkg/providers/v1/aws_fakes.go
  pkg/providers/v1/tags.go
  pkg/providers/v1/tags_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, needs-kind, ok-to-test, needs-triage

#464 Bump K8s libs to 0.25.0
  .ko.yaml
  Dockerfile
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, needs-kind, needs-triage

#466 control plane tolerations/selector
  charts/aws-cloud-controller-manager/values.yaml
Labels: kind/feature, release-note-action-required, approved, cncf-cla: yes, lgtm, size/XS, ok-to-test, needs-triage

#459 Automated cherry pick of #448: Handle InvalidInstanceID.NotFound when tagging resources
  pkg/providers/v1/aws_fakes.go
  pkg/providers/v1/tags.go
  pkg/providers/v1/tags_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, needs-kind, ok-to-test, needs-triage

#470 Fix broken helm chart
  charts/aws-cloud-controller-manager/Chart.yaml
  charts/aws-cloud-controller-manager/templates/daemonset.yaml
  charts/aws-cloud-controller-manager/values.yaml
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/XS, release-note, ok-to-test, needs-triage

#465 Chart dns policy
  charts/aws-cloud-controller-manager/templates/daemonset.yaml
  charts/aws-cloud-controller-manager/values.yaml
Labels: kind/bug, cncf-cla: yes, size/XS, release-note, ok-to-test, needs-triage

#468 Bump helm chart version
  charts/aws-cloud-controller-manager/Chart.yaml
Labels: kind/feature, approved, cncf-cla: yes, lgtm, do-not-merge/work-in-progress, size/XS, release-note-none, needs-ok-to-test, needs-triage

#471 Use ip address to describeENI for fargate nodes
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_fakes.go
  pkg/providers/v1/aws_test.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/S, release-note, ok-to-test, needs-triage

#473 Automated cherry pick of #471: Use ip address to describeENI for fargate nodes
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_fakes.go
  pkg/providers/v1/aws_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S, needs-kind, ok-to-test, needs-triage

#476 Automated cherry pick of #471: Use ip address to describeENI for fargate nodes
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_fakes.go
  pkg/providers/v1/aws_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S, needs-kind, ok-to-test, needs-triage

#474 Automated cherry pick of #471: Use ip address to describeENI for fargate nodes
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_fakes.go
  pkg/providers/v1/aws_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S, needs-kind, ok-to-test, needs-triage

#475 Automated cherry pick of #471: Use ip address to describeENI for fargate nodes
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_fakes.go
  pkg/providers/v1/aws_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S, needs-kind, ok-to-test, needs-triage

#472 Release version v1.25.0
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage
