Repository kubernetes/cloud-provider-aws, pull requests merged in 2022-03, with the labels that each got.

#312 Get e2e tests working in prow
  Makefile
  hack/e2e/run.sh
  hack/install-e2e-tools.sh
Labels: approved, cncf-cla: yes, lgtm, kind/failing-test, size/M, release-note-none

#313 add sts regional endpoint logic
  pkg/providers/v1/aws.go
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note, needs-kind, ok-to-test

#315 Automated cherry pick of #312: Fix e2e failures
  Makefile
  hack/e2e/run.sh
  hack/install-e2e-tools.sh
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, needs-kind, ok-to-test

#316 Fix 1.22 e2e failures
  hack/e2e/run.sh
Labels: approved, cncf-cla: yes, lgtm, kind/failing-test, size/XS, release-note-none

#314 Automated cherry pick of #313: add sts regional endpoint logic
  pkg/providers/v1/aws.go
Labels: approved, cncf-cla: yes, lgtm, size/M, needs-kind, ok-to-test

#317 Fix version
  Dockerfile
  Makefile
  cmd/aws-cloud-controller-manager/main.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/S, release-note

#319 Fix route controller create/delete spam: use instanceIDToNodeName in case node name != private DNS
  Makefile
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_routes.go
  pkg/providers/v1/aws_test.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/L, release-note, needs-triage

#320 Bump k8s version to v1.24.0-alpha.2
  Makefile
  go.mod
  go.sum
  hack/e2e/run.sh
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L, release-note-none, needs-triage

#308 Issue# 306: Added tagging controller
  .gitignore
  cmd/aws-cloud-controller-manager/main.go
  docs/TODO.md
  docs/tagging_controller.md
  pkg/controllers/options/resources.go
  pkg/controllers/options/tagging_controller.go
  pkg/controllers/tagging/tagging_controller.go
  pkg/controllers/tagging/tagging_controller_test.go
  pkg/controllers/tagging/tagging_controller_wrapper.go
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_fakes.go
  pkg/providers/v1/tags.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/XL, release-note-none, ok-to-test
