Repository kubernetes/cloud-provider-aws, pull requests merged in 2023-01, with the labels that each got.

#555 docs: use backticks to preserve wildcard chars
  docs/credential_provider.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/XS, release-note-none, needs-triage

#558 Add kishorj to the owners file
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#557 Update kOps command for creating clusters
  hack/e2e/run.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, needs-triage

#556 Release version v1.25.2
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, needs-triage

#559 Add dims to OWNERS file
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#502 Single goroutine access to the node cache
  pkg/providers/v1/instances.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/M, release-note, ok-to-test, needs-triage

#542 Merge tag and release GitHub workflows
  .github/workflows/release.yaml
  .github/workflows/tag-release.yml
  hack/tag-release.sh
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/M, release-note-none, triage/accepted

#439 update Makefile target for cloudbuild-artifacts
  Makefile
  cloudbuild.yaml
  hack/install-gsutil.sh
  hack/sha256
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L, release-note-none, ok-to-test, triage/accepted

#561 Automated cherry pick of #502: single update to node cache
  pkg/providers/v1/instances.go
Labels: approved, cncf-cla: yes, lgtm, size/M, needs-kind, needs-triage

#562 Release 1.25.3
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#563 Update README with latest releases
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/S, release-note-none, ok-to-test, needs-triage
