Repository kubernetes/cloud-provider-aws, pull requests merged in 2023-07, with the labels that each got.

#626 Update CCM 1.24 k8s deps to 1.24.15
  .ko.yaml
  Dockerfile
  go.mod
  go.sum
  hack/e2e/run.sh
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup, ok-to-test, needs-triage

#628 Bump version.txt to 1.24.15
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup, ok-to-test, needs-triage

#629 Update CCM 1.23 k8s deps to 1.23.17
  Dockerfile
  go.mod
  go.sum
  hack/e2e/run.sh
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, needs-ok-to-test, kind/cleanup, needs-triage

#630 Update CCM 1.25 k8s deps to 1.25.11
  .ko.yaml
  Dockerfile
  go.mod
  go.sum
  hack/e2e/run.sh
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup, ok-to-test, triage/accepted

#631 Update CCM 1.26 k8s deps to 1.26.6
  .ko.yaml
  Dockerfile
  go.mod
  go.sum
  hack/e2e/run.sh
  tests/e2e/go.mod
  tests/e2e/go.sum
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup, ok-to-test, triage/accepted

#632 Add cartermckinnon as a reviewer
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#634 Add authentication section to cred provider docs
  docs/credential_provider.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/XS, release-note-none, needs-triage

#621 chore: use out.String() instead of string(out.Bytes())
  cmd/ecr-credential-provider/plugin_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup, ok-to-test, triage/accepted
