Repository kubernetes/cloud-provider-aws, pull requests merged in 2023-08, with the labels that each got.

#641 Release v1.28.0
  cmd/aws-cloud-controller-manager/main.go
  go.mod
  go.sum
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, needs-kind, needs-triage

#642 Release v1.28.0
  cmd/aws-cloud-controller-manager/main.go
  go.mod
  go.sum
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, needs-kind, needs-triage

#636 Add template annotations to daemonset
  charts/aws-cloud-controller-manager/templates/daemonset.yaml
  charts/aws-cloud-controller-manager/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, needs-triage

#643 Update tagging controller's alias
  cmd/aws-cloud-controller-manager/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#644 Update tagging controller's alias
  cmd/aws-cloud-controller-manager/main.go
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#647 Fix url to reflect current directory structure / fix image tag version
  docs/getting_started.md
  examples/existing-cluster/base/aws-cloud-controller-manager-daemonset.yaml
  examples/existing-cluster/base/cluster-role.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup, needs-triage

#646 Bump Chart and appVersion
  charts/aws-cloud-controller-manager/Chart.yaml
  charts/aws-cloud-controller-manager/values.yaml
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-ok-to-test, needs-triage
