Repository kubernetes/cloud-provider-aws, pull requests merged in 2023-12, with the labels that each got.

#753 Drop Node event when EC2 instance does not exist
  pkg/controllers/tagging/tagging_controller.go
  pkg/controllers/tagging/tagging_controller_test.go
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_fakes.go
  pkg/providers/v1/tags.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/M, release-note-none, needs-triage

#755 Cherypick 1.28: Drop Node events when EC2 instance does not exist and node is not new
  pkg/controllers/tagging/tagging_controller.go
  pkg/controllers/tagging/tagging_controller_test.go
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_fakes.go
  pkg/providers/v1/tags.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/M, release-note-none, needs-triage

#756 Cherrypick 1.26: Drop Node events when EC2 instance does not exist and node is not new
  pkg/controllers/tagging/tagging_controller.go
  pkg/controllers/tagging/tagging_controller_test.go
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_fakes.go
  pkg/providers/v1/tags.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/M, release-note-none, needs-triage

#757 Cherrypick 1.27: Drop Node events when EC2 instance does not exist and node is not new
  pkg/controllers/tagging/tagging_controller.go
  pkg/controllers/tagging/tagging_controller_test.go
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_fakes.go
  pkg/providers/v1/tags.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/M, release-note-none, needs-triage

#764 update go version to 1.21.5
  .github/workflows/deps.yml
  .ko.yaml
  Dockerfile
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, needs-kind, needs-triage

#754 Enable prometheus provider for workqueue metrics
  pkg/controllers/tagging/tagging_controller.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/XS, release-note, needs-triage

#770 Bump k8s.io dependencies to v0.29.0
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, needs-kind, ok-to-test, needs-triage

#771 Release v1.29.0
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, needs-triage

#772 Bump default branch to 1.29.0
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#779 Changes to set minimum token permissions for the GITHUB_TOKEN in yaml files
  .github/workflows/helm_chart_release.yaml
  .github/workflows/tag.yml
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, needs-kind, ok-to-test, needs-triage

#782 Fix dependency review workflow
  .github/workflows/deps.yml
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, needs-kind, needs-triage

#781 Add dependabot configuration for default branch
  .github/dependabot.yaml
Labels: cncf-cla: yes, size/S, release-note-none, needs-kind, needs-triage

#788 Set labels for dependabot PR's, remove gomod rule
  .github/dependabot.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, needs-kind, needs-triage

#789 Add update-deps workflow
  .github/workflows/update-deps.yaml
  Makefile
  hack/update-deps.sh
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, needs-kind, needs-triage

#791 Update golang.org/x/crypto to v0.17.0
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note, needs-kind, ok-to-test, needs-triage

#793 Cherry pick #791 update golang.org/x/crypto to v0.17.0
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M, needs-ok-to-test, release-note, needs-kind, needs-triage

#794 Cherry pick #791 update golang.org/x/crypto to v0.17.0 and #764 update go version to 1.21.5
  .github/workflows/deps.yml
  .ko.yaml
  Dockerfile
  cloudbuild.yaml
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note, needs-kind, ok-to-test, needs-triage

#792 Cherry pick #791 update golang.org/x/crypto to v0.17.0 and #764 update go version to 1.21.5
  .github/workflows/deps.yml
  .ko.yaml
  Dockerfile
  cloudbuild.yaml
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note, needs-kind, ok-to-test, needs-triage

#795 Cherry pick #791 update golang.org/x/crypto to v0.17.0 and #764 update go version to 1.21.5
  .github/workflows/deps.yml
  .ko.yaml
  Dockerfile
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note, needs-kind, ok-to-test, needs-triage

#796 Cherry pick #791 update golang.org/x/crypto to v0.17.0 and #764 update go version to 1.21.5
  .github/workflows/deps.yml
  .ko.yaml
  Dockerfile
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note, needs-kind, ok-to-test, needs-triage

#797 Cherry pick #791 update golang.org/x/crypto to v0.17.0 and #764 update go version to 1.21.5
  .github/workflows/deps.yml
  .ko.yaml
  Dockerfile
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note, needs-kind, ok-to-test, needs-triage

#801 [release-1.23] Pin kubetest2-kops to last-working commit
  hack/install-e2e-tools.sh
Labels: kind/bug, cncf-cla: yes, size/XS, release-note-none, needs-triage

#798 Cherry pick #791 update golang.org/x/crypto to v0.17.0 and #764 update go version to 1.21.5
  .github/workflows/deps.yml
  .ko.yaml
  Dockerfile
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note, needs-kind, ok-to-test, needs-triage

#763 use subnets of ensured NLBs when update worker node SG rules
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_loadbalancer.go
  pkg/providers/v1/aws_test.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/M, release-note-none, needs-triage

#760 Cherrypick 1.23: Drop Node events when EC2 instance does not exist and node is not new
  pkg/controllers/tagging/tagging_controller.go
  pkg/controllers/tagging/tagging_controller_test.go
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_fakes.go
  pkg/providers/v1/tags.go
Labels: kind/bug, cncf-cla: yes, size/M, release-note-none, needs-triage

#759 Cherrypick 1.24: Drop Node events when EC2 instance does not exist and node is not new
  pkg/controllers/tagging/tagging_controller.go
  pkg/controllers/tagging/tagging_controller_test.go
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_fakes.go
  pkg/providers/v1/tags.go
Labels: kind/bug, cncf-cla: yes, size/M, release-note-none, needs-triage

#758 Cherrypick 1.25: Drop Node events when EC2 instance does not exist and node is not new
  pkg/controllers/tagging/tagging_controller.go
  pkg/controllers/tagging/tagging_controller_test.go
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_fakes.go
  pkg/providers/v1/tags.go
Labels: kind/bug, cncf-cla: yes, lgtm, size/M, release-note-none, needs-triage

#803 Cherrypick 1.23: use subnets of ensured NLBs when update worker node SG rules
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_loadbalancer.go
  pkg/providers/v1/aws_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, needs-kind, needs-triage

#804 Cherrypick 1.24: use subnets of ensured NLBs when update worker node SG rules
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_loadbalancer.go
  pkg/providers/v1/aws_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, needs-kind, needs-triage

#805 Cherrypick 1.25: use subnets of ensured NLBs when update worker node SG rules
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_loadbalancer.go
  pkg/providers/v1/aws_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, needs-kind, needs-triage

#808 Cherrypick 1.28: use subnets of ensured NLBs when update worker node SG rules
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_loadbalancer.go
  pkg/providers/v1/aws_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, needs-kind, needs-triage

#807 Cherrypick 1.27: use subnets of ensured NLBs when update worker node SG rules
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_loadbalancer.go
  pkg/providers/v1/aws_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, needs-kind, needs-triage

#806 Cherrypick 1.26: use subnets of ensured NLBs when update worker node SG rules
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_loadbalancer.go
  pkg/providers/v1/aws_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, needs-kind, needs-triage

#809 Cherrypick 1.29: use subnets of ensured NLBs when update worker node SG rules
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_loadbalancer.go
  pkg/providers/v1/aws_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, needs-kind, needs-triage

#811 Release 1.27.5
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, needs-triage

#813 Release 1.25.14
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, needs-triage

#814 Release 1.24.18
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, needs-triage

#812 Release 1.26.10
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, needs-triage

#810 Release 1.28.4
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, needs-triage

#815 Release 1.23.19
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, needs-triage

#816 Release 1.29.1
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, needs-triage

#817 Remove version matrix from README
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, needs-kind, needs-triage

#818 Backport to release 1.26 - fix: handle subnets with resource based naming more flexibly
  docs/prerequisites.md
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_test.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/M, release-note, ok-to-test, needs-triage
