Repository kubernetes/cloud-provider-aws, pull requests merged in 2023-06, with the labels that each got.

#609 Release 1.27.2
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, needs-triage

#615 Migrate away from google.com gcp project k8s-testimages
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup, needs-triage

#605 ignore invalid providerid for cache indexer
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_test.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/M, release-note-none, ok-to-test, triage/accepted

#616 Bump version.txt to 1.23.7
  hack/e2e/run.sh
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup, needs-triage

#617 Bump version.txt to 1.22.8
  OWNERS
  hack/e2e/run.sh
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#611 Bump version.txt to 1.24.5
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup, needs-triage

#618 Bump version.txt to 1.21.7
  OWNERS
  hack/e2e/run.sh
  hack/install-e2e-tools.sh
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup, needs-triage

#623 Update README with latest releases
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/XS, release-note-none, ok-to-test, needs-triage
