Repository kubernetes/cloud-provider-aws, pull requests merged in 2023-03, with the labels that each got.

#576 Fetch tags for later use when running cloudbuild
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, needs-kind, needs-triage

#578 Add empty .gcloudignore file
  .gcloudignore
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#579 Use default GCS location to upload artifacts
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#582 Don't update latest tag when uploading artifacts
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#583 Upload artifacts before generating the checksums
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#584 Release 1.26.1
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#565 Add support for IPv6 Fargate nodes
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_fakes.go
  pkg/providers/v1/aws_test.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/M, release-note-none, ok-to-test, needs-triage

#588 Update dependency golang.org/x/net to fix CVE-2022-41723
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup, ok-to-test, needs-triage
