Repository kubernetes/cloud-provider-aws, pull requests merged in 2023-04, with the labels that each got.

#591 Bump golang to 1.20.3.
  .ko.yaml
  Dockerfile
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#592 Remove release github workflow
  .github/workflows/tag-release.yml
  .github/workflows/tag.yml
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, needs-kind, needs-triage

#593 Bump kubernetes dependencies to 1.27.0 and other dependencies to latest
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, needs-kind, needs-triage

#594 Release 1.27.0
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#573 Simplifies configuring provider region
  .gitignore
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_fakes.go
  pkg/providers/v1/aws_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note, needs-kind, ok-to-test, needs-triage
