Repository kubernetes/cloud-provider-aws, pull requests merged in 2023-09, with the labels that each got.

#652 Script to test with latest k8s
  Makefile
  hack/switch-to-latest-k8s.sh
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/M, release-note-none, needs-triage

#653 Add new Makefile target to be able run CI jobs compiling the external cloud provider with latest k8s
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, needs-kind, needs-triage

#654 Always run against latest kubernetes version
  hack/e2e/run.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup, needs-triage

#655 Add code to generate junit xml in the right directory
  hack/e2e/run.sh
  tests/e2e/go.mod
  tests/e2e/go.sum
  tests/e2e/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, needs-kind, needs-triage

#649 Add cluster details to the sts through headers
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_utils.go
  pkg/providers/v1/aws_utils_test.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L, release-note, ok-to-test, needs-triage

#665 Reflect community ownership in default image name
  hack/e2e/run.sh
Labels: cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup, needs-triage

#663 Add cluster details to the sts through headers
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_utils.go
  pkg/providers/v1/aws_utils_test.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L, release-note, ok-to-test, needs-triage

#664 Add cluster details to the sts through headers
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_utils.go
  pkg/providers/v1/aws_utils_test.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L, release-note, ok-to-test, needs-triage

#658 Add cluster details to the sts through headers
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_utils.go
  pkg/providers/v1/aws_utils_test.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L, release-note, ok-to-test, needs-triage

#659 Add cluster details to the sts through headers
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_utils.go
  pkg/providers/v1/aws_utils_test.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L, release-note, ok-to-test, needs-triage

#667 Handle private ECR image references containing public.ecr.aws
  cmd/ecr-credential-provider/main.go
  cmd/ecr-credential-provider/main_test.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/L, release-note, needs-triage

#671 Add support for IPv6 Fargate nodes
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_fakes.go
  pkg/providers/v1/aws_test.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/M, release-note-none, ok-to-test, needs-triage

#672 Release 1.26.7
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, needs-triage
