Repository kubernetes/cloud-provider-aws, pull requests merged in 2023-11, with the labels that each got.

#713 [release-1.23] Add hakman, cartermckinnon
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#707 [release-1.23] Pin kops version to 1.28
  hack/e2e/run.sh
Labels: approved, cncf-cla: yes, lgtm, kind/failing-test, size/XS, release-note-none, needs-triage

#715 [release-1.28] Add cartermckinnon to approvers
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#716 [release-1.27] Add cartermckinnon
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#719 [release-1.24] Add cartermckinnon
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#717 [release-1.26] Add cartermckinnon
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#718 [release-1.25] Add cartermckinnon
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#712 fix(controllers/tagging): fix log format string
  pkg/controllers/tagging/tagging_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#699 [release-1.23] Automated cherry pick of #674: do not allow ec2 instance ID not found in tagging path
  pkg/providers/v1/tags.go
  pkg/providers/v1/tags_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note, needs-kind, ok-to-test, needs-triage

#661 [release-1.23] Cherry pick of #649: Add cluster details to the sts through headers
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_utils.go
  pkg/providers/v1/aws_utils_test.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L, release-note, ok-to-test, needs-triage

#720 update the go version to 1.21.3
  .ko.yaml
  Dockerfile
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, needs-triage

#722 Automated cherry pick of #675: Stricter dependency/security review & update go version #720: update the go version to 1.21.3
  .github/workflows/deps.yml
  .ko.yaml
  Dockerfile
  cloudbuild.yaml
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, needs-kind, needs-triage

#723 Automated cherry pick of #675: Stricter dependency/security review & update go version #720: update the go version to 1.21.3
  .github/workflows/deps.yml
  .ko.yaml
  Dockerfile
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, needs-kind, needs-triage

#721 Automated cherry pick of #675: Stricter dependency/security review & update go version #720: update the go version to 1.21.3
  .github/workflows/deps.yml
  .ko.yaml
  Dockerfile
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, needs-kind, needs-triage

#725 Automated cherry pick of #675: Stricter dependency/security review & update go version #720: update the go version to 1.21.3
  .github/workflows/deps.yml
  .ko.yaml
  Dockerfile
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, needs-kind, needs-triage

#726 Automated cherry pick of #675: Stricter dependency/security review & update go version #720: update the go version to 1.21.3
  .github/workflows/deps.yml
  .ko.yaml
  Dockerfile
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, needs-kind, needs-triage

#727 Automated cherry pick of #675: Stricter dependency/security review & update go version #720: update the go version to 1.21.3
  .github/workflows/deps.yml
  .ko.yaml
  Dockerfile
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, needs-kind, needs-triage

#650 Remove spurious space character in helm chart
  charts/aws-cloud-controller-manager/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup, ok-to-test, needs-triage

#730 Update the grpc and otel-go dependencies
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, needs-kind, ok-to-test, needs-triage

#731 fix(pkg/controllers/tagging): correct logging message for seconds
  pkg/controllers/tagging/tagging_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup, needs-triage

#739 Release 1.23.18
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, needs-triage

#732 cherry pick of #730: Update the grpc and otel-go dependencies
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, needs-kind, ok-to-test, needs-triage

#733 cherry pick of #730: Update the grpc and otel-go dependencies
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, needs-kind, ok-to-test, needs-triage

#734 cherry pick of #730 Update the grpc and otel-go dependencies
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, needs-kind, ok-to-test, needs-triage

#735 cherry pick of #730 Update the grpc dependencies
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, needs-kind, ok-to-test, needs-triage

#736 cherry pick of #730 Update the grpc dependencies
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, needs-kind, ok-to-test, needs-triage

#740 update otel-go dependency to v0.46.0
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, needs-kind, ok-to-test, needs-triage

#741 Update the go version to 1.21.4
  .github/workflows/deps.yml
  .ko.yaml
  Dockerfile
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note, needs-kind, ok-to-test, needs-triage

#738 Removed emeritus reviewers from SECURITY_CONTACTS
  OWNERS
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup, needs-triage

#745 cherry pick of #740 update otel-go dependency to v0.46.0 & #741 Update the go version to 1.21.4
  .github/workflows/deps.yml
  .ko.yaml
  Dockerfile
  cloudbuild.yaml
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note, needs-kind, ok-to-test, needs-triage

#744 cherry pick of #740 update otel-go dependency to v0.46.0 & #741 Update the go version to 1.21.4
  .github/workflows/deps.yml
  .ko.yaml
  Dockerfile
  cloudbuild.yaml
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note, needs-kind, ok-to-test, needs-triage

#743 cherry pick of #740 update otel-go dependency to v0.46.0 & #741 Update the go version to 1.21.4
  .github/workflows/deps.yml
  .ko.yaml
  Dockerfile
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note, needs-kind, ok-to-test, needs-triage

#750 Release 1.28.3
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, needs-triage

#747 Release 1.24.17
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, needs-triage

#749 Release 1.27.4
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, needs-triage

#751 Release 1.26.9
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, needs-triage

#748 Release 1.25.13
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, needs-triage
