Repository kubernetes/cloud-provider-aws, pull requests merged in 2023-10, with the labels that each got.

#674 Do not allow EC2 instance ID NotFound to succeed tagging
  pkg/providers/v1/tags.go
  pkg/providers/v1/tags_test.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/S, release-note-none, ok-to-test, needs-triage

#675 Stricter dependency/security review & update go version
  .github/workflows/deps.yml
  Dockerfile
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup, triage/accepted

#677 Removes v2 provider
  cmd/aws-cloud-controller-manager/main.go
  pkg/providers/v2/cloud.go
  pkg/providers/v2/cloud_test.go
  pkg/providers/v2/instances.go
  pkg/providers/v2/instances_test.go
  pkg/providers/v2/tags.go
  pkg/providers/v2/tags_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL, release-note, kind/cleanup, ok-to-test, needs-triage

#678 Moves mocks out of v2 provider directory
  cmd/ecr-credential-provider/main_test.go
  pkg/mocks/mock_ecr.go
  pkg/providers/v2/mocks/mock_ec2.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup, ok-to-test, needs-triage

#673 Remove ecr pattern restriction
  cmd/ecr-credential-provider/main.go
  cmd/ecr-credential-provider/main_test.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/M, release-note, ok-to-test, needs-triage

#681 Automated cherry pick of #667: Handle private ECR image references containing public.ecr.aws
  cmd/ecr-credential-provider/main.go
  cmd/ecr-credential-provider/main_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, needs-kind, needs-triage

#685 [release-1.26] Update k8s.io/cloud-provider
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup, needs-triage

#689 [release-1.25] Update k8s.io/cloud-provider
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup, needs-triage

#686 [release-1.27] Update k8s.io/cloud-provider
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup, needs-triage

#688 [release-1.28] Update k8s.io/cloud-provider
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup, needs-triage

#691 [release-1.24] Automated cherry pick of #557: Update kOps command for creating clusters
  hack/e2e/run.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#690 [release-1.24] Update k8s.io/cloud-provider, golang.org/x/net
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup, needs-triage

#662 Add cluster details to the sts through headers
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_utils.go
  pkg/providers/v1/aws_utils_test.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L, release-note, ok-to-test, needs-triage

#694 [release-1.28] Automated cherry pick of #674: do not allow ec2 instance ID not found in tagging path
  pkg/providers/v1/tags.go
  pkg/providers/v1/tags_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note, needs-kind, ok-to-test, needs-triage

#697 [release-1.25] Automated cherry pick of #674: do not allow ec2 instance ID not found in tagging path
  pkg/providers/v1/tags.go
  pkg/providers/v1/tags_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note, needs-kind, ok-to-test, needs-triage

#698 [release-1.24] Automated cherry pick of #674: do not allow ec2 instance ID not found in tagging path
  pkg/providers/v1/tags.go
  pkg/providers/v1/tags_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note, needs-kind, ok-to-test, needs-triage

#695 [release-1.27] Automated cherry pick of #674: do not allow ec2 instance ID not found in tagging path
  pkg/providers/v1/tags.go
  pkg/providers/v1/tags_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note, needs-kind, ok-to-test, needs-triage

#696 [release-1.26] Automated cherry pick of #674: do not allow ec2 instance ID not found in tagging path
  pkg/providers/v1/tags.go
  pkg/providers/v1/tags_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note, needs-kind, ok-to-test, needs-triage

#705 Update OWNERS to include mmerkes as a reviewer
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#700 Release 1.24.16
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#704 Release 1.28.2
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#702 Release 1.26.8
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#701 Release 1.25.12
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#703 Release 1.27.3
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage
