Repository kubernetes/cloud-provider-aws, pull requests merged in 2023-05, with the labels that each got.

#601 Update Readme and fix the kops cluster create example
  docs/getting_started.md
  examples/kops-new-cluster/base/cluster.yaml
  examples/kops-new-cluster/overlays/cloud-controller-manager/kustomization.yaml
  hack/kops-example.sh
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/S, release-note-none, ok-to-test, needs-triage

#598 fix: handle subnets with resource based naming more flexibly
  docs/prerequisites.md
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_test.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/L, release-note-none, needs-triage

#607 Add version flag to ecr-credential-provider
  Makefile
  cmd/ecr-credential-provider/main.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/M, release-note, ok-to-test, needs-triage
