Repository kubernetes/cloud-provider-aws, pull requests merged in 2024-04, with the labels that each got.

#897 (cleanup): Move types to their own files
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_disk.go
  pkg/providers/v1/aws_ec2.go
  pkg/providers/v1/aws_instance.go
  pkg/providers/v1/aws_sdk.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XXL, kind/cleanup, needs-triage

#852 Moving OWNERS to emeritus
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup, needs-triage

#899 updating deps to v1.30.0
  .github/workflows/deps.yml
  .github/workflows/update-deps.yaml
  .ko.yaml
  Dockerfile
  cloudbuild.yaml
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, needs-kind, ok-to-test, needs-triage

#898 (cleanup): remove unused volume handling
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_disk.go
  pkg/providers/v1/aws_ec2.go
  pkg/providers/v1/aws_test.go
  pkg/providers/v1/device_allocator.go
  pkg/providers/v1/device_allocator_test.go
  pkg/providers/v1/instances.go
  pkg/providers/v1/volumes.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL, release-note, kind/cleanup, needs-triage

#900 bumping go to 1.22.2
  .github/workflows/deps.yml
  .github/workflows/update-deps.yaml
  .ko.yaml
  Dockerfile
  cloudbuild.yaml
  go.mod
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, needs-kind, ok-to-test, needs-triage

#902 (cleanup): remove legacy instance group interface
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_instancegroups.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup, needs-triage

#903 Release 1.30.0
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage
