Repository kubernetes/cloud-provider-aws, pull requests merged in 2024-08, with the labels that each got.

#1013 Release 1.31.0-rc.0
  go.mod
  go.sum
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, needs-kind, ok-to-test, needs-triage

#954 Allow user to specify Registry Pull Secret
  charts/aws-cloud-controller-manager/templates/daemonset.yaml
  charts/aws-cloud-controller-manager/values.yaml
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/XS, release-note, ok-to-test, triage/accepted

#1016 Update upstream dependencies to 1.31.0
  go.mod
  go.sum
  hack/e2e/run.sh
  tests/e2e/go.mod
  tests/e2e/go.sum
  tests/e2e/loadbalancer.go
  tests/e2e/nodes.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XXL, needs-kind, ok-to-test, needs-triage

#1017 Release v1.31.0
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, needs-triage

#1018 Bump default branch to 1.31.0
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, needs-triage

#752 Ensure removal of security group rules on deleting load balancers
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_fakes.go
  pkg/providers/v1/aws_test.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/L, release-note, triage/accepted
