Repository kubernetes/cloud-provider-aws, pull requests merged in 2024-06, with the labels that each got.

#944 docs(footer): Add trademark disclaimer
  docs/overrides/partials/copyright.html
  mkdocs.yml
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/M, release-note-none, needs-ok-to-test, needs-triage

#941 Update k8s dependencies to 0.27.14
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note, kind/cleanup, ok-to-test, needs-triage

#940 Update k8s dependencies to 0.29.5
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note, kind/cleanup, ok-to-test, needs-triage

#943 Update k8s dependencies to 0.30.1
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note, kind/cleanup, ok-to-test, needs-triage

#942 Update k8s dependencies to 0.28.10
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note, kind/cleanup, ok-to-test, needs-triage

#949 Bump golang version to 1.21.11 for release-1.29 branch
  .github/workflows/deps.yml
  .ko.yaml
  Dockerfile
  cloudbuild.yaml
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/S, release-note-none, needs-triage

#948 Bump golang version to 1.22.4 for release-1.30 branch
  .ko.yaml
  Dockerfile
  cloudbuild.yaml
  go.mod
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/S, release-note-none, needs-triage

#946 Automated cherry pick of #917: extract fargate into a standalone file
  pkg/controllers/tagging/tagging_controller.go
  pkg/controllers/tagging/tagging_controller_test.go
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_fakes.go
  pkg/providers/v1/aws_instance.go
  pkg/providers/v1/aws_loadbalancer_test.go
  pkg/providers/v1/aws_sdk.go
  pkg/providers/v1/aws_test.go
  pkg/providers/v1/config/config.go
  pkg/providers/v1/iface/types.go
  pkg/providers/v1/instances.go
  pkg/providers/v1/tags.go
  pkg/providers/v1/tags_test.go
  pkg/providers/v1/variant/fargate/fargate.go
  pkg/providers/v1/variant/variant.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XXL, kind/cleanup, needs-triage

#937 Grant cloud-controller-manager RBAC permissions for HTTP port access
  charts/aws-cloud-controller-manager/values.yaml
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/S, release-note, ok-to-test, needs-triage

#953 Add kmala to the owners file
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#962 [release-1.29] Add kmala to the owners file
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#955 [release-1.30] Add kmala to the owners file
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#961 [release-1.28] Add kmala to the owners file
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#960 [release-1.27] Add kmala to the owners file
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#959 [release-1.26] Add kmala to the owners file
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#958 [release-1.25] Add kmala to the owners file
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#957 [release-1.24] Add kmala to the owners file
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#956 [release-1.23] Add kmala to the owners file
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#965 Update aws sdk go to support new partiton
  .github/workflows/deps.yml
  .ko.yaml
  Dockerfile
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, needs-kind, needs-triage

#967 Update aws sdk go to support new partiton
  .github/workflows/deps.yml
  .ko.yaml
  Dockerfile
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, needs-kind, needs-triage

#968 Update aws sdk go to support new partiton
  .github/workflows/deps.yml
  .ko.yaml
  Dockerfile
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, needs-kind, needs-triage

#969 Update aws sdk go to support new partiton
  .github/workflows/deps.yml
  .ko.yaml
  Dockerfile
  cloudbuild.yaml
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, needs-kind, needs-triage

#970 Update aws sdk go to support new partiton
  .github/workflows/deps.yml
  .ko.yaml
  Dockerfile
  cloudbuild.yaml
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, needs-kind, needs-triage

#971 Update aws sdk go to support new partiton
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, needs-kind, needs-triage

#966 Update aws sdk go to support new partiton
  .github/workflows/deps.yml
  .ko.yaml
  Dockerfile
  go.mod
  go.sum
  hack/e2e/run.sh
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, needs-kind, needs-triage

#974 Release 1.25.16
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#978 Release 1.29.4
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#973 Release 1.23.21
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#977 Release 1.28.7
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#976 Release 1.27.8
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#975 Release 1.26.13
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#979 Release 1.24.20
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#981 add support for new aws partitions in credential provider
  cmd/ecr-credential-provider/main.go
  cmd/ecr-credential-provider/main_test.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/S, release-note-none, needs-triage

#982 Automated cherry pick of #981: add support for new aws partitions in credential provider
  cmd/ecr-credential-provider/main.go
  cmd/ecr-credential-provider/main_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, needs-kind, needs-triage

#983 Automated cherry pick of #981: add support for new aws partitions in credential provider
  cmd/ecr-credential-provider/main.go
  cmd/ecr-credential-provider/main_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, needs-kind, needs-triage

#984 Automated cherry pick of #981: add support for new aws partitions in credential provider
  cmd/ecr-credential-provider/main.go
  cmd/ecr-credential-provider/main_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, needs-kind, needs-triage

#985 Automated cherry pick of #981: add support for new aws partitions in credential provider
  cmd/ecr-credential-provider/main.go
  cmd/ecr-credential-provider/main_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, needs-kind, needs-triage

#989 Release 1.30.2
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#988 Release 1.29.5
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#987 Release 1.28.8
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#986 Release 1.27.9
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#990 Log useful information about the cluster and the instance
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_sdk.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup, triage/accepted
