Repository kubernetes/cloud-provider-aws, pull requests merged in 2024-11, with the labels that each got.

#1036 Bump go mod version
  .github/workflows/deps.yml
  .ko.yaml
  Dockerfile
  cloudbuild.yaml
  go.mod
  go.sum
  hack/e2e/run.sh
  tests/e2e/go.mod
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup, ok-to-test, needs-triage

#1041 Migrates InstanceTopologyManager to use sdk v2
  go.mod
  go.sum
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_ec2.go
  pkg/providers/v1/aws_fakes.go
  pkg/providers/v1/aws_test.go
  pkg/providers/v1/iface/types.go
  pkg/providers/v1/instances_v2.go
  pkg/providers/v1/instances_v2_test.go
  pkg/providers/v1/topology_test.go
  pkg/resourcemanagers/topology.go
  pkg/resourcemanagers/topology_mock.go
  pkg/resourcemanagers/topology_test.go
  pkg/services/aws_ec2.go
  pkg/services/aws_ec2_mock.go
  pkg/services/errors_mock.go
Labels: approved, cncf-cla: yes, lgtm, size/XL, release-note-none, kind/cleanup, triage/accepted

#1042 Cherry-picked not topology labels for 1.31
  .github/workflows/update-deps.yaml
  cmd/ecr-credential-provider/main.go
  cmd/ecr-credential-provider/main_test.go
  docs/prerequisites.md
  go.mod
  go.sum
  pkg/mocks/mock_ecr.go
  pkg/providers/v1/aws.go
  pkg/providers/v1/iface/types.go
  pkg/providers/v1/instances_v2.go
  pkg/providers/v1/instances_v2_test.go
  pkg/providers/v1/well_known_labels.go
  pkg/resourcemanagers/topology.go
  pkg/resourcemanagers/topology_mock.go
  pkg/resourcemanagers/topology_test.go
  pkg/services/aws_ec2.go
  pkg/services/aws_ec2_mock.go
  pkg/services/errors_mock.go
  tests/e2e/nodes.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/XL, release-note, needs-triage

#1044 Cherry-picked not topology labels for 1.30
  cmd/ecr-credential-provider/main.go
  cmd/ecr-credential-provider/main_test.go
  docs/prerequisites.md
  go.mod
  go.sum
  pkg/mocks/mock_ecr.go
  pkg/providers/v1/aws.go
  pkg/providers/v1/iface/types.go
  pkg/providers/v1/instances_v2.go
  pkg/providers/v1/instances_v2_test.go
  pkg/providers/v1/well_known_labels.go
  pkg/resourcemanagers/topology.go
  pkg/resourcemanagers/topology_mock.go
  pkg/resourcemanagers/topology_test.go
  pkg/services/aws_ec2.go
  pkg/services/aws_ec2_mock.go
  pkg/services/errors_mock.go
  tests/e2e/nodes.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/XL, release-note, needs-triage

#1045 Release v1.30.4
  version.txt
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-triage

#1046 Release v1.31.2
  version.txt
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-triage

#1048 Fixes typo and formatting in development.md
  docs/development.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/XS, release-note-none, triage/accepted

#1049 Removes unused autoscaling code
  Makefile
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_fakes.go
  pkg/providers/v1/aws_sdk.go
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup, triage/accepted

#1051 Release 1.28.10
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, triage/accepted

#1052 Release 1.27.10
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, needs-triage

#1050 Release v1.29.7
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, needs-triage

#1053 Release 1.26.14
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, needs-triage

#1054 Fixes EC2 SDK v2 client configuration to assume role properly
  go.mod
  go.sum
  pkg/providers/v1/aws.go
  pkg/resourcemanagers/topology.go
  pkg/resourcemanagers/topology_test.go
  pkg/services/aws_ec2.go
  pkg/services/aws_sts.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/L, release-note-none, triage/accepted

#1056 Backports EC2 SDK v2 client fix
  go.mod
  go.sum
  pkg/providers/v1/aws.go
  pkg/resourcemanagers/topology.go
  pkg/resourcemanagers/topology_test.go
  pkg/services/aws_ec2.go
  pkg/services/aws_sts.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/L, release-note-none, needs-triage

#1057 Backports fix to EC2 SDK v2 client
  go.mod
  go.sum
  pkg/providers/v1/aws.go
  pkg/resourcemanagers/topology.go
  pkg/resourcemanagers/topology_test.go
  pkg/services/aws_ec2.go
  pkg/services/aws_sts.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/L, release-note-none, needs-triage

#1059 Creates 1.31.3 release
  version.txt
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-triage

#1058 Creates 1.30.5 release
  version.txt
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-triage

#1060 Gracefully handles getting instance topology and unhandled variants
  pkg/providers/v1/instances_v2.go
  pkg/providers/v1/instances_v2_test.go
  pkg/resourcemanagers/topology.go
  pkg/resourcemanagers/topology_test.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/M, release-note-none, triage/accepted

#1062 Cherry picks gracefully handles getting instance topology and unhandled variants in 1.30
  pkg/providers/v1/instances_v2.go
  pkg/providers/v1/instances_v2_test.go
  pkg/resourcemanagers/topology.go
  pkg/resourcemanagers/topology_test.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/M, release-note-none, needs-triage

#1063 Cherry picks gracefully handles getting instance topology and unhandled variants in 1.31
  pkg/providers/v1/instances_v2.go
  pkg/providers/v1/instances_v2_test.go
  pkg/resourcemanagers/topology.go
  pkg/resourcemanagers/topology_test.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/M, release-note-none, needs-triage

#1065 Cuts 1.30.6 release
  version.txt
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/XS, release-note-none, triage/accepted

#1066 Cuts 1.31.4 release
  version.txt
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/XS, release-note-none, triage/accepted

#1064 Update to latest ko
  Makefile
  hack/install-ko.sh
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-triage
