Repository kubernetes/cloud-provider-aws, pull requests merged in 2024-05, with the labels that each got.

#910 CVE-2023-45288: bump golang.org/x/net to v0.24.0
  go.mod
  go.sum
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup, ok-to-test, needs-triage

#919 Go version workflows
  .github/workflows/deps.yml
  .github/workflows/update-deps.yaml
  .ko.yaml
  Dockerfile
  cloudbuild.yaml
  go.mod
  tests/e2e/go.mod
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup, triage/accepted

#909 Ensure that addresses are added in network device index order
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_fakes.go
  pkg/providers/v1/aws_test.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/M, release-note, ok-to-test, needs-triage

#865 Add missing annotations on https://cloud-provider-aws.sigs.k8s.io/service_controller/
  docs/service_controller.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/S, release-note-none, needs-ok-to-test, needs-triage

#925 Automated cherry pick of #909: Ensure that addresses are added in network device index order
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_fakes.go
  pkg/providers/v1/aws_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M, needs-kind, ok-to-test, needs-triage

#924 Automated cherry pick of #909: Ensure that addresses are added in network device index order
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_fakes.go
  pkg/providers/v1/aws_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M, needs-kind, ok-to-test, needs-triage

#922 Automated cherry pick of #909: Ensure that addresses are added in network device index order
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_fakes.go
  pkg/providers/v1/aws_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M, needs-kind, ok-to-test, needs-triage

#923 Automated cherry pick of #909: Ensure that addresses are added in network device index order
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_fakes.go
  pkg/providers/v1/aws_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M, needs-kind, ok-to-test, needs-triage

#921 Automated cherry pick of #909: Ensure that addresses are added in network device index order
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_fakes.go
  pkg/providers/v1/aws_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M, needs-kind, ok-to-test, needs-triage

#930 Release 1.27.7
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, needs-triage

#927 Release 1.30.1
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, needs-triage

#929 Release 1.28.6
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, needs-triage

#931 Release 1.26.12
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, needs-triage

#928 Release 1.29.3
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, needs-triage
