Repository kubernetes/cloud-provider-aws, pull requests merged in 2024-02, with the labels that each got.

#847 Stop marking helm releases as "Latest release"
  .github/workflows/helm_chart_release.yaml
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-ok-to-test, needs-triage

#845 Implements InstancesV2 interface
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_test.go
  pkg/providers/v1/instances_v2.go
  pkg/providers/v1/instances_v2_test.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L, release-note, kind/cleanup, needs-triage

#851 Update OWNERS
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup, needs-triage
