Repository kubernetes/cloud-provider-aws, pull requests merged in 2024-03, with the labels that each got.

#854 Get zone information from cache
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_fakes.go
  pkg/providers/v1/aws_test.go
  pkg/providers/v1/instances_v2_test.go
  pkg/providers/v1/zones.go
  pkg/providers/v1/zones_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup, triage/accepted

#858 Use 1.30 alpha.3 k8s packages
  go.mod
  go.sum
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L, release-note-none, triage/accepted

#855 Add zone-id topology label to nodes
  pkg/providers/v1/instances_v2.go
  pkg/providers/v1/instances_v2_test.go
  pkg/providers/v1/well_known_labels.go
  pkg/providers/v1/zones.go
  pkg/providers/v1/zones_test.go
  tests/e2e/nodes.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L, release-note, triage/accepted

#863 updating deps to v0.30.0-beta.0
  .github/workflows/deps.yml
  .github/workflows/update-deps.yaml
  .ko.yaml
  Dockerfile
  cloudbuild.yaml
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, needs-kind, ok-to-test, needs-triage

#864 updating version.txt to 1.30.0-beta.0
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-ok-to-test, needs-kind, needs-triage

#874 Bump github.com/golang/protobuf v1.5.4, google.golang.org/protobuf v1.33.0
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note, needs-kind, ok-to-test, needs-triage

#873 Bump github.com/golang/protobuf v1.5.4, google.golang.org/protobuf v1.33.0
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note, needs-kind, ok-to-test, needs-triage

#872 Bump github.com/golang/protobuf v1.5.4, google.golang.org/protobuf v1.33.0
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note, needs-kind, ok-to-test, needs-triage

#867 Bump github.com/golang/protobuf v1.5.4, google.golang.org/protobuf v1.33.0
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note, needs-kind, ok-to-test, needs-triage

#868 Bump github.com/golang/protobuf v1.5.4, google.golang.org/protobuf v1.33.0
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note, needs-kind, ok-to-test, needs-triage

#870 Bump github.com/golang/protobuf v1.5.4, google.golang.org/protobuf v1.33.0
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note, needs-kind, ok-to-test, needs-triage

#871 Bump github.com/golang/protobuf v1.5.4, google.golang.org/protobuf v1.33.0
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note, needs-kind, ok-to-test, needs-triage

#883 Release 1.29.2
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, needs-triage

#880 Release 1.26.11
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, needs-triage

#879 Release 1.25.15
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, needs-triage

#878 Release 1.24.19
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, needs-triage

#881 Release 1.27.6
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, needs-triage

#877 Release 1.23.20
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, needs-triage

#882 Release 1.28.5
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, needs-triage

#886 Bump k8s lib to 0.30.0-rc.0
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, needs-kind, ok-to-test, needs-triage

#887 Bump tag to 1.30.0-rc.0
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-ok-to-test, needs-kind, needs-triage

#889 Support rc tag
  hack/tag-release.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-ok-to-test, needs-kind, needs-triage
