Repository kubernetes/cloud-provider-aws, pull requests merged in 2024-12, with the labels that each got.

#1069 Update ECR Regex to support new dual stack endpoints + tests
  cmd/ecr-credential-provider/main.go
  cmd/ecr-credential-provider/main_test.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/M, release-note, ok-to-test, needs-triage

#1068 Release 1.32.0-rc.2
  .ko.yaml
  Dockerfile
  cloudbuild.yaml
  go.mod
  go.sum
  tests/e2e/go.mod
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, needs-kind, ok-to-test, needs-triage

#1072 Automated cherry pick of #1069: Update ECR Regex to support new dual stack endpoints, modify
  cmd/ecr-credential-provider/main.go
  cmd/ecr-credential-provider/main_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M, needs-kind, ok-to-test, needs-triage

#1073 Automated cherry pick of #1069: Update ECR Regex to support new dual stack endpoints, modify
  cmd/ecr-credential-provider/main.go
  cmd/ecr-credential-provider/main_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M, needs-kind, ok-to-test, needs-triage

#1074 Automated cherry pick of #1069: Update ECR Regex to support new dual stack endpoints, modify
  cmd/ecr-credential-provider/main.go
  cmd/ecr-credential-provider/main_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M, needs-kind, ok-to-test, needs-triage

#1075 Automated cherry pick of #1069: Update ECR Regex to support new dual stack endpoints, modify
  cmd/ecr-credential-provider/main.go
  cmd/ecr-credential-provider/main_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M, needs-kind, ok-to-test, needs-triage

#1078 Release version 1.30.7
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, needs-ok-to-test, release-note, needs-kind, needs-triage

#1080 Version bump 1.32.0-rc.3
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, needs-ok-to-test, release-note, needs-kind, needs-triage

#1079 Release version 1.31.5
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, needs-ok-to-test, release-note, needs-kind, needs-triage

#1076 Version 1.28.11 release
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note, needs-kind, ok-to-test, needs-triage

#1077 Release version 1.29.8
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note, needs-kind, ok-to-test, needs-triage

#1082 release 1.32.0
  go.mod
  go.sum
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, needs-kind, ok-to-test, needs-triage

#622 Update health checks to use Kube-Proxy when no other configuration is provided
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_loadbalancer.go
  pkg/providers/v1/aws_test.go
  pkg/providers/v1/config/config.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note, needs-kind, needs-triage
