Repository kubernetes/cloud-provider-aws, pull requests merged in 2025-01, with the labels that each got.

#1088 Update dependencies to resolve CVE-2024-45338
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note, kind/cleanup, ok-to-test, triage/accepted

#1089 Use typed client-go constructors for rate-limit related objects
  pkg/controllers/tagging/tagging_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup, needs-triage

#1091 optimize tagging controller workqueue handling
  pkg/controllers/tagging/metrics.go
  pkg/controllers/tagging/tagging_controller.go
  pkg/controllers/tagging/tagging_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note, needs-kind, needs-triage

#1092 Automated cherry pick of #1091: optimize tagging controller workqueue handling
  pkg/controllers/tagging/metrics.go
  pkg/controllers/tagging/tagging_controller.go
  pkg/controllers/tagging/tagging_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, needs-kind, needs-triage

#1030 ecr-credential-provider: Fix warning about no region in image ref
  cmd/ecr-credential-provider/main.go
Labels: approved, kind/bug, cncf-cla: yes, lifecycle/stale, lgtm, size/XS, release-note-none, triage/accepted
