Repository kubernetes/cloud-provider-aws, pull requests merged in 2025-09, with the labels that each got.

#1245 Update ec2 sdk version to latest
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, needs-kind, ok-to-test, needs-triage

#1250 bump version to 1.30.9
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup, ok-to-test, needs-triage

#1252 bump version to 1.31.8
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup, ok-to-test, needs-triage

#1249 bump version to 1.33.2
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup, ok-to-test, needs-triage

#1251 bump version to 1.32.5
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup, ok-to-test, needs-triage

#1253 release 1.34.0
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, needs-triage

#1256 e2e: bump dependencies to more recent k8s lib
  tests/e2e/ecr_creds.go
  tests/e2e/go.mod
  tests/e2e/go.sum
  tests/e2e/loadbalancer.go
  tests/e2e/nodes.go
Labels: approved, cncf-cla: yes, lgtm, kind/failing-test, release-note-none, size/XXL, kind/cleanup, ok-to-test, needs-triage

#1260 Fix the batched describe insance method for instance not found case
  pkg/providers/v1/describe_instance_batch.go
  pkg/providers/v1/instances_v2_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, needs-kind, needs-triage

#1263 Update cloud-controller-manager image version to v1.34.0
  charts/aws-cloud-controller-manager/Chart.yaml
  charts/aws-cloud-controller-manager/values.yaml
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/XS, needs-ok-to-test, release-note, needs-triage
