Repository kubernetes/cloud-provider-aws, pull requests merged in 2025-10, with the labels that each got.

#1277 Update SDK version to latest
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note, needs-kind, needs-triage

#1266 Bump go sdk to 1.24.7
  .ko.yaml
  Dockerfile
  cloudbuild.yaml
  go.mod
  tests/e2e/go.mod
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, needs-kind, needs-triage

#1270 Automated cherry pick of #1266: bump go sdk to 1.24.7 for CVE
  .ko.yaml
  Dockerfile
  cloudbuild.yaml
  go.mod
  tests/e2e/go.mod
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, needs-kind, needs-triage

#1273 Automated cherry pick of #1266: bump go sdk to 1.24.7 for CVE
  .ko.yaml
  Dockerfile
  cloudbuild.yaml
  go.mod
  tests/e2e/go.mod
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, needs-kind, needs-triage

#1274 Automated cherry pick of #1266: bump go sdk to 1.24.7 for CVE
  .ko.yaml
  Dockerfile
  cloudbuild.yaml
  go.mod
  tests/e2e/go.mod
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, needs-kind, needs-triage

#1275 Automated cherry pick of #1266: bump go sdk to 1.24.7 for CVE
  .ko.yaml
  Dockerfile
  cloudbuild.yaml
  go.mod
  tests/e2e/go.mod
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, needs-kind, needs-triage

#1232 Add support private ipv4 addresses annotation for NLB
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_loadbalancer.go
  pkg/providers/v1/aws_loadbalancer_test.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/M, release-note-none, ok-to-test, needs-triage
