Repository kubernetes/cloud-provider-aws, pull requests merged in 2025-02, with the labels that each got.

#1100 Requires node topology labels to be set for known supported instance …
  .gitignore
  pkg/providers/v1/aws.go
  pkg/providers/v1/config/config.go
  pkg/providers/v1/instances_v2.go
  pkg/providers/v1/instances_v2_test.go
  pkg/resourcemanagers/topology.go
  pkg/resourcemanagers/topology_mock.go
  pkg/resourcemanagers/topology_test.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/L, release-note-none, triage/accepted

#1106 Updates go to 1.23.6 to resolve vulnerabilities
  .github/workflows/deps.yml
  .github/workflows/update-deps.yaml
  .ko.yaml
  Dockerfile
  cloudbuild.yaml
  go.mod
  go.sum
  tests/e2e/go.mod
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup, needs-triage

#1103 1.32: Requires node topology labels to be set for known supported instance …
  .gitignore
  pkg/providers/v1/aws.go
  pkg/providers/v1/config/config.go
  pkg/providers/v1/instances_v2.go
  pkg/providers/v1/instances_v2_test.go
  pkg/resourcemanagers/topology.go
  pkg/resourcemanagers/topology_mock.go
  pkg/resourcemanagers/topology_test.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/L, release-note-none, needs-triage

#1104 1.31: Requires node topology labels to be set for known supported instance …
  .gitignore
  pkg/providers/v1/aws.go
  pkg/providers/v1/config/config.go
  pkg/providers/v1/instances_v2.go
  pkg/providers/v1/instances_v2_test.go
  pkg/resourcemanagers/topology.go
  pkg/resourcemanagers/topology_mock.go
  pkg/resourcemanagers/topology_test.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/L, release-note-none, needs-triage

#1105 1.30: Requires node topology labels to be set for known supported instance …
  .gitignore
  pkg/providers/v1/aws.go
  pkg/providers/v1/config/config.go
  pkg/providers/v1/instances_v2.go
  pkg/providers/v1/instances_v2_test.go
  pkg/resourcemanagers/topology.go
  pkg/resourcemanagers/topology_mock.go
  pkg/resourcemanagers/topology_test.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/L, release-note-none, needs-triage

#1107 Release version 1.30.8
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, needs-triage

#1109 Optimize node controller describe instances calls
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_fakes.go
  pkg/providers/v1/instances_v2.go
  pkg/providers/v1/instances_v2_test.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/M, release-note-none, ok-to-test, needs-triage

#1110 Automated cherry pick of #1109: Optimize node controller describe instances calls
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_fakes.go
  pkg/providers/v1/instances_v2.go
  pkg/providers/v1/instances_v2_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, needs-kind, ok-to-test, needs-triage

#1111 Release 1.32.2
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, needs-triage
