Repository kubernetes/cloud-provider-aws, pull requests merged in 2025-07, with the labels that each got.

#1179 Bump version to 1.33.1
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note, needs-kind, ok-to-test, needs-triage

#1189 Release version 1.31.7
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, needs-triage

#1180 Automated cherry pick of #1146: upgraded to ec2 v2, buggy #1157: Update ELB and ELBV2 packages to AWS SDK Go V2 #1169: aws sdk go upgrade #1177: update aws & awserr to go sdk v2
  THIRD-PARTY-LICENSES
  go.mod
  go.sum
  pkg/controllers/tagging/tagging_controller.go
  pkg/controllers/tagging/tagging_controller_test.go
  pkg/controllers/tagging/tagging_controller_wrapper.go
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_assumerole_provider.go
  pkg/providers/v1/aws_assumerole_provider_test.go
  pkg/providers/v1/aws_ec2.go
  pkg/providers/v1/aws_fakes.go
  pkg/providers/v1/aws_instance.go
  pkg/providers/v1/aws_loadbalancer.go
  pkg/providers/v1/aws_loadbalancer_test.go
  pkg/providers/v1/aws_routes.go
  pkg/providers/v1/aws_sdk.go
  pkg/providers/v1/aws_sdk_test.go
  pkg/providers/v1/aws_test.go
  pkg/providers/v1/aws_utils.go
  pkg/providers/v1/config/config.go
  pkg/providers/v1/create_tags_batch.go
  pkg/providers/v1/delete_tags_batch.go
  pkg/providers/v1/iface/types.go
  pkg/providers/v1/instances.go
  pkg/providers/v1/instances_test.go
  pkg/providers/v1/instances_v2.go
  pkg/providers/v1/instances_v2_test.go
  pkg/providers/v1/log_handler.go
  pkg/providers/v1/retry_handler.go
  pkg/providers/v1/retry_handler_test.go
  pkg/providers/v1/sets_ippermissions.go
  pkg/providers/v1/sets_ippermissions_test.go
  pkg/providers/v1/tags.go
  pkg/providers/v1/tags_test.go
  pkg/providers/v1/topology.go
  pkg/providers/v1/topology_mock.go
  pkg/providers/v1/topology_test.go
  pkg/providers/v1/variant/fargate/fargate.go
  pkg/providers/v1/variant/variant.go
  pkg/providers/v1/zones.go
  pkg/providers/v1/zones_test.go
  pkg/services/aws_ec2.go
  pkg/services/aws_ec2_mock.go
  pkg/services/aws_sts.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL, release-note, needs-kind, ok-to-test, needs-triage

#1191 Cherrypick #1135 to release 1.33
  .ko.yaml
  Dockerfile
  cloudbuild.yaml
  go.mod
  tests/e2e/go.mod
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, needs-kind, needs-triage

#1193 bump version to 1.32.4
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note, needs-kind, ok-to-test, needs-triage

#1196 Cleanup unused autoscaling client
  pkg/providers/v1/aws.go
  pkg/providers/v1/aws_fakes.go
  pkg/providers/v1/aws_sdk.go
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note, kind/cleanup, ok-to-test, needs-triage

#1194 Adding yue9944882 to eks team approver
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/XS, release-note-none, needs-triage

#1205 doc/devel: enhance docs to use in existing cluster
  docs/development.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/M, needs-ok-to-test, release-note, needs-triage

#1207 fix/lb SG rule update failures when service port is changed
  pkg/providers/v1/sets_ippermissions.go
  pkg/providers/v1/sets_ippermissions_test.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/L, release-note, ok-to-test, needs-triage

#1213 chore(chart): update version
  charts/aws-cloud-controller-manager/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup, needs-triage
