Repository kubernetes/cloud-provider-aws, pull requests merged in 2025-04, with the labels that each got.

#1129 Release 1.33.0-beta.0
  .ko.yaml
  Dockerfile
  cloudbuild.yaml
  go.mod
  go.sum
  tests/e2e/go.mod
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, needs-kind, ok-to-test, needs-triage

#1131 Release v1.33.0-rc.0
  go.mod
  go.sum
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, needs-kind, ok-to-test, needs-triage

#1130 Release version 1.31.6
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, needs-triage

#1116 feat: add tagging controller delays and work queue size metrics
  pkg/controllers/tagging/metrics.go
  pkg/controllers/tagging/tagging_controller.go
  pkg/controllers/tagging/tagging_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, needs-kind, ok-to-test, needs-triage

#1134 Automated cherry pick of #1116: feat: add tagging controller delays and work queue size #1120: Batch tagging controller create/delete tags calls #1126: Enable concurrent worker syncs for tagging controller
  .ko.yaml
  Dockerfile
  cloudbuild.yaml
  go.mod
  go.sum
  pkg/controllers/options/tagging_controller.go
  pkg/controllers/tagging/metrics.go
  pkg/controllers/tagging/tagging_controller.go
  pkg/controllers/tagging/tagging_controller_test.go
  pkg/controllers/tagging/tagging_controller_wrapper.go
  pkg/providers/v1/aws.go
  pkg/providers/v1/batcher/batch_test.go
  pkg/providers/v1/batcher/batcher.go
  pkg/providers/v1/create_tags_batch.go
  pkg/providers/v1/delete_tags_batch.go
  pkg/providers/v1/tags.go
  tests/e2e/go.mod
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XXL, needs-kind, ok-to-test, needs-triage

#1140 Automated cherry pick of #1116: feat: add tagging controller delays and work queue size #1120: Batch tagging controller create/delete tags calls
  go.mod
  go.sum
  pkg/controllers/options/tagging_controller.go
  pkg/controllers/tagging/metrics.go
  pkg/controllers/tagging/tagging_controller.go
  pkg/controllers/tagging/tagging_controller_test.go
  pkg/controllers/tagging/tagging_controller_wrapper.go
  pkg/providers/v1/aws.go
  pkg/providers/v1/batcher/batch_test.go
  pkg/providers/v1/batcher/batcher.go
  pkg/providers/v1/create_tags_batch.go
  pkg/providers/v1/delete_tags_batch.go
  pkg/providers/v1/tags.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XXL, needs-kind, ok-to-test, needs-triage

#1142 1.33.0 release
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, needs-kind, ok-to-test, needs-triage

#1143 update version txt
  version.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, ok-to-test, needs-triage

#1144 Bump k8s.io dependencies to v1.33.0
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, needs-kind, ok-to-test, needs-triage
