Repository kubernetes/cloud-provider-aws, pull requests merged in 2025-03, with the labels that each got.

#1123 Bump golang.org/x/oauth2 to v0.27.0
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, needs-kind, needs-triage

#1124 Bump golang.org/x/crypto to v0.35.0
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, needs-kind, needs-triage

#1125 Bump go runner to v2.3.1-go1.23.2-bookworm.0
  .ko.yaml
  Dockerfile
  cloudbuild.yaml
  go.mod
  tests/e2e/go.mod
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup, needs-triage

#1126 Enable concurrent workers for tagging controller
  pkg/controllers/options/tagging_controller.go
  pkg/controllers/tagging/tagging_controller.go
  pkg/controllers/tagging/tagging_controller_test.go
  pkg/controllers/tagging/tagging_controller_wrapper.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/S, release-note, ok-to-test, triage/accepted
